/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Uploads a file, optionally attaching it to a location or a building
 */
export const UploadAssetQueryParams = zod.object({
  "title": zod.string().optional(),
  "resourceType": zod.enum(['location', 'building']).optional(),
  "resourceId": zod.string().optional()
})

export const UploadAssetHeader = zod.object({
  "Content-Disposition": zod.string()
})

export const UploadAssetResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "byteSize": zod.int(),
  "contentType": zod.string(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "height": zod.int().optional(),
  "id": zod.string(),
  "originalFilename": zod.string(),
  "title": zod.string(),
  "type": zod.enum(['image', 'video', 'audio', 'document', 'other']),
  "width": zod.int().optional()
})

/**
 * @summary Returns the bytes of the asset with the provided id
 */
export const GetAssetContentParams = zod.object({
  "id": zod.string()
})

export const GetAssetContentResponse = zod.unknown()

