/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all manufacturers
 */
export const ListManufacturersResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
})
export const ListManufacturersResponse = zod.array(ListManufacturersResponseItem)

/**
 * @summary Creates a manufacturer
 */



export const CreateManufacturerBody = zod.object({
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "website": zod.string().optional()
})

export const CreateManufacturerResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
})

/**
 * Refused while any device model is made by the manufacturer.
 * @summary Deletes the manufacturer with the provided id
 */
export const DeleteManufacturerParams = zod.object({
  "id": zod.string()
})

export const DeleteManufacturerResponse = zod.void()

/**
 * @summary Returns the manufacturer with the provided id
 */
export const GetManufacturerParams = zod.object({
  "id": zod.string()
})

export const GetManufacturerResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
})

/**
 * @summary Updates the manufacturer with the provided id
 */
export const UpdateManufacturerParams = zod.object({
  "id": zod.string()
})




export const UpdateManufacturerBody = zod.object({
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "website": zod.string().optional()
})

export const UpdateManufacturerResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
})

