/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all buildings, optionally narrowed to a single location
 */
export const ListBuildingsQueryParams = zod.object({
  "status": zod.array(zod.enum(['planned', 'active', 'decommissioned', 'archived'])).optional().describe('Lifecycle statuses to include. Defaults to planned and active, which keeps decommissioned and archived buildings off the map and out of the default lists without hiding them from a direct lookup.'),
  "locationId": zod.string().optional().describe('Only return buildings sitting in this location. Omit it to list buildings across every location.')
})

export const listBuildingsResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const listBuildingsResponseRepresentativePointCoordinatesMin = 2;
export const listBuildingsResponseRepresentativePointCoordinatesMax = 3;



export const ListBuildingsResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(listBuildingsResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "locationId": zod.string().optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(listBuildingsResponseRepresentativePointCoordinatesMin).max(listBuildingsResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})
export const ListBuildingsResponse = zod.array(ListBuildingsResponseItem)

/**
 * @summary Creates a building
 */
export const createBuildingBodyAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');



export const CreateBuildingBody = zod.object({
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(createBuildingBodyAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "locationId": zod.string().optional().describe('The location this building stands in; omit for one that has not been placed yet'),
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived'])
})

export const createBuildingResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const createBuildingResponseRepresentativePointCoordinatesMin = 2;
export const createBuildingResponseRepresentativePointCoordinatesMax = 3;



export const CreateBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(createBuildingResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "locationId": zod.string().optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(createBuildingResponseRepresentativePointCoordinatesMin).max(createBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Deletes the building with the provided id
 */
export const DeleteBuildingParams = zod.object({
  "id": zod.string()
})

export const DeleteBuildingResponse = zod.void()

/**
 * @summary Returns building with the provided id
 */
export const GetBuildingParams = zod.object({
  "id": zod.string()
})

export const getBuildingResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const getBuildingResponseRepresentativePointCoordinatesMin = 2;
export const getBuildingResponseRepresentativePointCoordinatesMax = 3;



export const GetBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(getBuildingResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "locationId": zod.string().optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(getBuildingResponseRepresentativePointCoordinatesMin).max(getBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Updates the building with the provided id
 */
export const UpdateBuildingParams = zod.object({
  "id": zod.string()
})

export const updateBuildingBodyAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');



export const UpdateBuildingBody = zod.object({
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateBuildingBodyAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "locationId": zod.string().optional().describe('The location this building stands in; omit to detach it from the one it sits in now'),
  "name": zod.string().min(1),
  "notes": zod.string().optional()
})

export const updateBuildingResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const updateBuildingResponseRepresentativePointCoordinatesMin = 2;
export const updateBuildingResponseRepresentativePointCoordinatesMax = 3;



export const UpdateBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateBuildingResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "locationId": zod.string().optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateBuildingResponseRepresentativePointCoordinatesMin).max(updateBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Updates the building status of the building with provided id
 */
export const UpdateBuildingStatusParams = zod.object({
  "id": zod.string()
})

export const UpdateBuildingStatusBody = zod.object({
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived'])
})

export const updateBuildingStatusResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const updateBuildingStatusResponseRepresentativePointCoordinatesMin = 2;
export const updateBuildingStatusResponseRepresentativePointCoordinatesMax = 3;



export const UpdateBuildingStatusResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateBuildingStatusResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "locationId": zod.string().optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateBuildingStatusResponseRepresentativePointCoordinatesMin).max(updateBuildingStatusResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

