/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all buildings
 */
export const listBuildingsResponseRepresentativePointCoordinatesMin = 2;
export const listBuildingsResponseRepresentativePointCoordinatesMax = 3;



export const ListBuildingsResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(listBuildingsResponseRepresentativePointCoordinatesMin).max(listBuildingsResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "updatedAt": zod.iso.datetime({"offset":true})
})
export const ListBuildingsResponse = zod.array(ListBuildingsResponseItem)

/**
 * @summary Creates a building
 */



export const CreateBuildingBody = zod.object({
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "name": zod.string().min(1),
  "notes": zod.string().optional()
})

export const createBuildingResponseRepresentativePointCoordinatesMin = 2;
export const createBuildingResponseRepresentativePointCoordinatesMax = 3;



export const CreateBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(createBuildingResponseRepresentativePointCoordinatesMin).max(createBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Soft deletes the building with the provided id
 */
export const DeleteBuildingParams = zod.object({
  "id": zod.string()
})

export const DeleteBuildingResponse = zod.void()

/**
 * @summary Returns building with the provided id
 */
export const GetBuildingParams = zod.object({
  "id": zod.string()
})

export const getBuildingResponseRepresentativePointCoordinatesMin = 2;
export const getBuildingResponseRepresentativePointCoordinatesMax = 3;



export const GetBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(getBuildingResponseRepresentativePointCoordinatesMin).max(getBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Updates the building with the provided id
 */
export const UpdateBuildingParams = zod.object({
  "id": zod.string()
})




export const UpdateBuildingBody = zod.object({
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "name": zod.string().min(1),
  "notes": zod.string().optional()
})

export const updateBuildingResponseRepresentativePointCoordinatesMin = 2;
export const updateBuildingResponseRepresentativePointCoordinatesMax = 3;



export const UpdateBuildingResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "footprint": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateBuildingResponseRepresentativePointCoordinatesMin).max(updateBuildingResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}),
  "updatedAt": zod.iso.datetime({"offset":true})
})

