/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Log in with username and password
 */

export const loginBodyUsernameMin = 3;



export const LoginBody = zod.object({
  "password": zod.string().min(1).describe('Account password'),
  "username": zod.string().min(loginBodyUsernameMin).describe('Account username (case-insensitive)')
})

export const LoginResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

/**
 * @summary Log out and end the current session
 */
export const LogoutResponse = zod.void()

/**
 * @summary Return the currently authenticated user
 */
export const GetCurrentUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

