/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all user accounts
 */
export const ListUsersResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "permissions": zod.array(zod.string()),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})
export const ListUsersResponse = zod.array(ListUsersResponseItem)

/**
 * @summary Creates a user account
 */
export const createUserBodyPasswordMin = 8;

export const createUserBodyUsernameMin = 3;



export const CreateUserBody = zod.object({
  "email": zod.email().describe('Account email address'),
  "password": zod.string().min(createUserBodyPasswordMin).describe('Initial account password'),
  "role": zod.enum(['viewer', 'editor', 'admin']).describe('Role the account starts with'),
  "username": zod.string().min(createUserBodyUsernameMin).describe('Account username')
})

export const CreateUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "permissions": zod.array(zod.string()),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

/**
 * @summary Deletes the user account with the provided id
 */
export const DeleteUserParams = zod.object({
  "id": zod.string()
})

export const DeleteUserResponse = zod.void()

/**
 * @summary Returns the user account with the provided id
 */
export const GetUserParams = zod.object({
  "id": zod.string()
})

export const GetUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "permissions": zod.array(zod.string()),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

/**
 * @summary Updates the username and email of the account with the provided id
 */
export const UpdateUserParams = zod.object({
  "id": zod.string()
})

export const updateUserBodyUsernameMin = 3;



export const UpdateUserBody = zod.object({
  "email": zod.email().describe('New account email address'),
  "username": zod.string().min(updateUserBodyUsernameMin).describe('New account username')
})

export const UpdateUserResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "permissions": zod.array(zod.string()),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

/**
 * @summary Sets a new password on the account with the provided id
 */
export const ResetUserPasswordParams = zod.object({
  "id": zod.string()
})

export const resetUserPasswordBodyNewPasswordMin = 8;



export const ResetUserPasswordBody = zod.object({
  "newPassword": zod.string().min(resetUserPasswordBodyNewPasswordMin).describe('New account password')
})

export const ResetUserPasswordResponse = zod.void()

/**
 * @summary Changes the role of the account with the provided id
 */
export const UpdateUserRoleParams = zod.object({
  "id": zod.string()
})

export const UpdateUserRoleBody = zod.object({
  "role": zod.enum(['viewer', 'editor', 'admin']).describe('Role to move the account to')
})

export const UpdateUserRoleResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "created_at": zod.iso.datetime({"offset":true}),
  "email": zod.string(),
  "id": zod.string(),
  "permissions": zod.array(zod.string()),
  "role": zod.string(),
  "updated_at": zod.iso.datetime({"offset":true}),
  "username": zod.string()
})

