/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorModel,
  ManufacturerRequest,
  ManufacturerResponse
} from '../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listManufacturersResponse200 = {
  data: ManufacturerResponse[]
  status: 200
}

export type listManufacturersResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listManufacturersResponseSuccess = (listManufacturersResponse200) & {
  headers: Headers;
};
export type listManufacturersResponseError = (listManufacturersResponseDefault) & {
  headers: Headers;
};

export type listManufacturersResponse = (listManufacturersResponseSuccess | listManufacturersResponseError)

export const getListManufacturersUrl = () => {




  return `/api/manufacturers`
}

/**
 * @summary Returns all manufacturers
 */
export const listManufacturers = async ( options?: RequestInit): Promise<listManufacturersResponse> => {

  const res = await fetch(getListManufacturersUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listManufacturersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listManufacturersResponse
}





export const getListManufacturersQueryKey = () => {
    return [
    `/api/manufacturers`
    ] as const;
    }


export const getListManufacturersQueryOptions = <TData = Awaited<ReturnType<typeof listManufacturers>>, TError = ErrorModel>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListManufacturersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listManufacturers>>> = ({ signal }) => listManufacturers({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListManufacturersQueryResult = NonNullable<Awaited<ReturnType<typeof listManufacturers>>>
export type ListManufacturersQueryError = ErrorModel


export function useListManufacturers<TData = Awaited<ReturnType<typeof listManufacturers>>, TError = ErrorModel>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listManufacturers>>,
          TError,
          Awaited<ReturnType<typeof listManufacturers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListManufacturers<TData = Awaited<ReturnType<typeof listManufacturers>>, TError = ErrorModel>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listManufacturers>>,
          TError,
          Awaited<ReturnType<typeof listManufacturers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListManufacturers<TData = Awaited<ReturnType<typeof listManufacturers>>, TError = ErrorModel>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all manufacturers
 */

export function useListManufacturers<TData = Awaited<ReturnType<typeof listManufacturers>>, TError = ErrorModel>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listManufacturers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListManufacturersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createManufacturerResponse201 = {
  data: ManufacturerResponse
  status: 201
}

export type createManufacturerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 201>
}

export type createManufacturerResponseSuccess = (createManufacturerResponse201) & {
  headers: Headers;
};
export type createManufacturerResponseError = (createManufacturerResponseDefault) & {
  headers: Headers;
};

export type createManufacturerResponse = (createManufacturerResponseSuccess | createManufacturerResponseError)

export const getCreateManufacturerUrl = () => {




  return `/api/manufacturers`
}

/**
 * @summary Creates a manufacturer
 */
export const createManufacturer = async (manufacturerRequest: NonReadonly<ManufacturerRequest>, options?: RequestInit): Promise<createManufacturerResponse> => {

  const res = await fetch(getCreateManufacturerUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(manufacturerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createManufacturerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createManufacturerResponse
}





export const getCreateManufacturerMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManufacturer>>, TError,{data: NonReadonly<ManufacturerRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createManufacturer>>, TError,{data: NonReadonly<ManufacturerRequest>}, TContext> => {

const mutationKey = ['createManufacturer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createManufacturer>>, {data: NonReadonly<ManufacturerRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createManufacturer(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateManufacturerMutationResult = NonNullable<Awaited<ReturnType<typeof createManufacturer>>>
    export type CreateManufacturerMutationBody = NonReadonly<ManufacturerRequest>
    export type CreateManufacturerMutationError = ErrorModel

    /**
 * @summary Creates a manufacturer
 */
export const useCreateManufacturer = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createManufacturer>>, TError,{data: NonReadonly<ManufacturerRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createManufacturer>>,
        TError,
        {data: NonReadonly<ManufacturerRequest>},
        TContext
      > => {
      return useMutation(getCreateManufacturerMutationOptions(options), queryClient);
    }
    export type deleteManufacturerResponse204 = {
  data: void
  status: 204
}

export type deleteManufacturerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteManufacturerResponseSuccess = (deleteManufacturerResponse204) & {
  headers: Headers;
};
export type deleteManufacturerResponseError = (deleteManufacturerResponseDefault) & {
  headers: Headers;
};

export type deleteManufacturerResponse = (deleteManufacturerResponseSuccess | deleteManufacturerResponseError)

export const getDeleteManufacturerUrl = (id: string,) => {




  return `/api/manufacturers/${id}`
}

/**
 * Refused while any device model is made by the manufacturer.
 * @summary Deletes the manufacturer with the provided id
 */
export const deleteManufacturer = async (id: string, options?: RequestInit): Promise<deleteManufacturerResponse> => {

  const res = await fetch(getDeleteManufacturerUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteManufacturerResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteManufacturerResponse
}





export const getDeleteManufacturerMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteManufacturer>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteManufacturer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteManufacturer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteManufacturer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteManufacturer(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteManufacturerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteManufacturer>>>

    export type DeleteManufacturerMutationError = ErrorModel

    /**
 * @summary Deletes the manufacturer with the provided id
 */
export const useDeleteManufacturer = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteManufacturer>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteManufacturer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteManufacturerMutationOptions(options), queryClient);
    }
    export type getManufacturerResponse200 = {
  data: ManufacturerResponse
  status: 200
}

export type getManufacturerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getManufacturerResponseSuccess = (getManufacturerResponse200) & {
  headers: Headers;
};
export type getManufacturerResponseError = (getManufacturerResponseDefault) & {
  headers: Headers;
};

export type getManufacturerResponse = (getManufacturerResponseSuccess | getManufacturerResponseError)

export const getGetManufacturerUrl = (id: string,) => {




  return `/api/manufacturers/${id}`
}

/**
 * @summary Returns the manufacturer with the provided id
 */
export const getManufacturer = async (id: string, options?: RequestInit): Promise<getManufacturerResponse> => {

  const res = await fetch(getGetManufacturerUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getManufacturerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getManufacturerResponse
}





export const getGetManufacturerQueryKey = (id: string,) => {
    return [
    `/api/manufacturers/${id}`
    ] as const;
    }


export const getGetManufacturerQueryOptions = <TData = Awaited<ReturnType<typeof getManufacturer>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetManufacturerQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getManufacturer>>> = ({ signal }) => getManufacturer(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetManufacturerQueryResult = NonNullable<Awaited<ReturnType<typeof getManufacturer>>>
export type GetManufacturerQueryError = ErrorModel


export function useGetManufacturer<TData = Awaited<ReturnType<typeof getManufacturer>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturer>>,
          TError,
          Awaited<ReturnType<typeof getManufacturer>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetManufacturer<TData = Awaited<ReturnType<typeof getManufacturer>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getManufacturer>>,
          TError,
          Awaited<ReturnType<typeof getManufacturer>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetManufacturer<TData = Awaited<ReturnType<typeof getManufacturer>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the manufacturer with the provided id
 */

export function useGetManufacturer<TData = Awaited<ReturnType<typeof getManufacturer>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getManufacturer>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetManufacturerQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateManufacturerResponse200 = {
  data: ManufacturerResponse
  status: 200
}

export type updateManufacturerResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateManufacturerResponseSuccess = (updateManufacturerResponse200) & {
  headers: Headers;
};
export type updateManufacturerResponseError = (updateManufacturerResponseDefault) & {
  headers: Headers;
};

export type updateManufacturerResponse = (updateManufacturerResponseSuccess | updateManufacturerResponseError)

export const getUpdateManufacturerUrl = (id: string,) => {




  return `/api/manufacturers/${id}`
}

/**
 * @summary Updates the manufacturer with the provided id
 */
export const updateManufacturer = async (id: string,
    manufacturerRequest: NonReadonly<ManufacturerRequest>, options?: RequestInit): Promise<updateManufacturerResponse> => {

  const res = await fetch(getUpdateManufacturerUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(manufacturerRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateManufacturerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateManufacturerResponse
}





export const getUpdateManufacturerMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateManufacturer>>, TError,{id: string;data: NonReadonly<ManufacturerRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateManufacturer>>, TError,{id: string;data: NonReadonly<ManufacturerRequest>}, TContext> => {

const mutationKey = ['updateManufacturer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateManufacturer>>, {id: string;data: NonReadonly<ManufacturerRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateManufacturer(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateManufacturerMutationResult = NonNullable<Awaited<ReturnType<typeof updateManufacturer>>>
    export type UpdateManufacturerMutationBody = NonReadonly<ManufacturerRequest>
    export type UpdateManufacturerMutationError = ErrorModel

    /**
 * @summary Updates the manufacturer with the provided id
 */
export const useUpdateManufacturer = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateManufacturer>>, TError,{id: string;data: NonReadonly<ManufacturerRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateManufacturer>>,
        TError,
        {id: string;data: NonReadonly<ManufacturerRequest>},
        TContext
      > => {
      return useMutation(getUpdateManufacturerMutationOptions(options), queryClient);
    }
