/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface Address {
  city?: string;
  /**
     * ISO 3166-1 alpha-2 country code
     * @pattern ^[A-Za-z]{2}$
     */
  country?: string;
  street?: string;
  /** Postal code, in whatever shape the country writes it */
  zip?: string;
}
