/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { AssetResponseType } from './assetResponseType.ts';

export interface AssetResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  byteSize: number;
  contentType: string;
  createdAt: string;
  height?: number;
  id: string;
  originalFilename: string;
  title: string;
  type: AssetResponseType;
  width?: number;
}
