/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { AssetResponse } from './assetResponse.ts';

export interface AssetAttachmentResponse {
  asset: AssetResponse;
  caption?: string;
  id: string;
}
