/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type AssetResponseType = typeof AssetResponseType[keyof typeof AssetResponseType];


export const AssetResponseType = {
  image: 'image',
  video: 'video',
  audio: 'audio',
  document: 'document',
  other: 'other',
} as const;
