/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { Address } from './address.ts';
import type { BuildingResponseStatus } from './buildingResponseStatus.ts';
import type { MultiPolygon } from './multiPolygon.ts';
import type { Point } from './point.ts';

export interface BuildingResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  address?: Address;
  createdAt: string;
  footprint: MultiPolygon;
  id: string;
  locationId?: string;
  name: string;
  notes?: string;
  representativePoint: Point;
  status: BuildingResponseStatus;
  updatedAt: string;
}
