/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type CreateLocationRequestStatus = typeof CreateLocationRequestStatus[keyof typeof CreateLocationRequestStatus];


export const CreateLocationRequestStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
