/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

/**
 * Role the account starts with
 */
export type CreateUserInputBodyRole = typeof CreateUserInputBodyRole[keyof typeof CreateUserInputBodyRole];


export const CreateUserInputBodyRole = {
  viewer: 'viewer',
  editor: 'editor',
  admin: 'admin',
} as const;
