/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { CreateUserInputBodyRole } from './createUserInputBodyRole.ts';

export interface CreateUserInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Account email address */
  email: string;
  /**
     * Initial account password
     * @minLength 8
     */
  password: string;
  /** Role the account starts with */
  role: CreateUserInputBodyRole;
  /**
     * Account username
     * @minLength 3
     */
  username: string;
}
