/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type CreateDeviceModelRequestStatus = typeof CreateDeviceModelRequestStatus[keyof typeof CreateDeviceModelRequestStatus];


export const CreateDeviceModelRequestStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
