/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { CreateBuildingRequestStatus } from './createBuildingRequestStatus.ts';
import type { MultiPolygon } from './multiPolygon.ts';

export interface CreateBuildingRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  footprint: MultiPolygon;
  /** @minLength 1 */
  name: string;
  notes?: string;
  status: CreateBuildingRequestStatus;
}
