/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

/**
 * The highest PoE standard the model supplies; only with poeOut
 */
export type DeviceModelResponsePoeOutStandard = typeof DeviceModelResponsePoeOutStandard[keyof typeof DeviceModelResponsePoeOutStandard];


export const DeviceModelResponsePoeOutStandard = {
  af: 'af',
  at: 'at',
  bt: 'bt',
  passive: 'passive',
} as const;
