/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { DeviceModelResponseMounting } from './deviceModelResponseMounting.ts';
import type { DeviceModelResponseStatus } from './deviceModelResponseStatus.ts';
import type { DeviceTypeResponse } from './deviceTypeResponse.ts';
import type { ManufacturerResponse } from './manufacturerResponse.ts';

export interface DeviceModelResponse {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  createdAt: string;
  depthMm?: number;
  deviceType: DeviceTypeResponse;
  heightMm?: number;
  id: string;
  manufacturer: ManufacturerResponse;
  mounting?: DeviceModelResponseMounting;
  name: string;
  notes?: string;
  partNumber?: string;
  /** Can be powered over Ethernet */
  poeIn: boolean;
  /** Can power other devices over Ethernet */
  poeOut: boolean;
  /** Maximum power draw in watts */
  powerWattsMax?: number;
  rackUnits?: number;
  status: DeviceModelResponseStatus;
  updatedAt: string;
  widthMm?: number;
}
