/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type DeviceModelResponseStatus = typeof DeviceModelResponseStatus[keyof typeof DeviceModelResponseStatus];


export const DeviceModelResponseStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
