/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface DeviceTypeResponse {
  code: string;
  color: string;
  /** A lucide icon name */
  icon: string;
  id: string;
  name: string;
  sortOrder: number;
}
