/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type GetAssetContentVariant = typeof GetAssetContentVariant[keyof typeof GetAssetContentVariant];


export const GetAssetContentVariant = {
  original: 'original',
  thumb: 'thumb',
  preview: 'preview',
} as const;
