/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { GetAssetContentVariant } from './getAssetContentVariant.ts';

export type GetAssetContentParams = {
variant?: GetAssetContentVariant;
};
