/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { ListAssetsResourceType } from './listAssetsResourceType.ts';

export type ListAssetsParams = {
resourceType: ListAssetsResourceType;
resourceId: string;
};
