/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type ListLocationsStatusItem = typeof ListLocationsStatusItem[keyof typeof ListLocationsStatusItem];


export const ListLocationsStatusItem = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
