/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type ListDeviceModelsStatusItem = typeof ListDeviceModelsStatusItem[keyof typeof ListDeviceModelsStatusItem];


export const ListDeviceModelsStatusItem = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
