/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { ListDeviceModelsMounting } from './listDeviceModelsMounting.ts';
import type { ListDeviceModelsStatusItem } from './listDeviceModelsStatusItem.ts';

export type ListDeviceModelsParams = {
/**
 * Lifecycle statuses to include. Defaults to planned and active, which keeps models that are no longer available/used out of the default lists without hiding them from a direct lookup.
 */
status?: ListDeviceModelsStatusItem[];
/**
 * Only return models of this device type. Omit it to list models of every type.
 */
deviceTypeId?: string;
/**
 * Only return models made by this manufacturer. Omit it to list models of every manufacturer.
 */
manufacturerId?: string;
/**
 * Only return models mounted this way. Omit it to list models however they are mounted.
 */
mounting?: ListDeviceModelsMounting;
};
