/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type ListLocationTreeStatusItem = typeof ListLocationTreeStatusItem[keyof typeof ListLocationTreeStatusItem];


export const ListLocationTreeStatusItem = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
