/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type ListAssetsResourceType = typeof ListAssetsResourceType[keyof typeof ListAssetsResourceType];


export const ListAssetsResourceType = {
  location: 'location',
  building: 'building',
  device_model: 'device_model',
} as const;
