/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type ListBuildingsStatusItem = typeof ListBuildingsStatusItem[keyof typeof ListBuildingsStatusItem];


export const ListBuildingsStatusItem = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
