/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { ListLocationTreeStatusItem } from './listLocationTreeStatusItem.ts';

export type ListLocationTreeParams = {
/**
 * Lifecycle statuses to include. Defaults to planned and active, which keeps decommissioned and archived locations off the map and out of the default lists without hiding them from a direct lookup.
 */
status?: ListLocationTreeStatusItem[];
};
