/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type LocationTreeResponseStatus = typeof LocationTreeResponseStatus[keyof typeof LocationTreeResponseStatus];


export const LocationTreeResponseStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
