/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { Address } from './address.ts';
import type { LocationTreeResponseStatus } from './locationTreeResponseStatus.ts';
import type { MultiPolygon } from './multiPolygon.ts';
import type { Point } from './point.ts';

export interface LocationTreeResponse {
  address?: Address;
  area?: MultiPolygon;
  createdAt: string;
  depth: number;
  id: string;
  name: string;
  notes?: string;
  parentId?: string;
  representativePoint?: Point;
  representativePointManual: boolean;
  status: LocationTreeResponseStatus;
  updatedAt: string;
}
