/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type LocationResponseStatus = typeof LocationResponseStatus[keyof typeof LocationResponseStatus];


export const LocationResponseStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
