/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface LoginInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Account password
     * @minLength 1
     */
  password: string;
  /**
     * Account username (case-insensitive)
     * @minLength 3
     */
  username: string;
}
