/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { MultiPolygonType } from './multiPolygonType.ts';

export interface MultiPolygon {
  /** An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring's first entry is its exterior boundary and the rest are holes */
  coordinates: number[][][][];
  /** GeoJSON geometry type */
  type: MultiPolygonType;
}
