/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

/**
 * GeoJSON geometry type
 */
export type MultiPolygonType = typeof MultiPolygonType[keyof typeof MultiPolygonType];


export const MultiPolygonType = {
  MultiPolygon: 'MultiPolygon',
} as const;
