/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

/**
 * GeoJSON geometry type
 */
export type PointType = typeof PointType[keyof typeof PointType];


export const PointType = {
  Point: 'Point',
} as const;
