/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { PointType } from './pointType.ts';

export interface Point {
  /**
     * A [longitude, latitude] position, optionally with elevation
     * @minItems 2
     * @maxItems 3
     */
  coordinates: number[];
  /** GeoJSON geometry type */
  type: PointType;
}
