/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type UpdateLocationStatusRequestStatus = typeof UpdateLocationStatusRequestStatus[keyof typeof UpdateLocationStatusRequestStatus];


export const UpdateLocationStatusRequestStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
