/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UpdateBuildingStatusRequestStatus } from './updateBuildingStatusRequestStatus.ts';

export interface UpdateBuildingStatusRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  status: UpdateBuildingStatusRequestStatus;
}
