/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { Address } from './address.ts';
import type { MultiPolygon } from './multiPolygon.ts';
import type { Point } from './point.ts';

export interface UpdateLocationRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  address?: Address;
  /** The boundary of the location; omit for one whose extent nobody has established yet */
  area?: MultiPolygon;
  /** @minLength 1 */
  name: string;
  notes?: string;
  /** The location this one sits inside; omit to move it to the top level */
  parentId?: string;
  representativePoint?: Point;
}
