/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type UpdateDeviceModelStatusRequestStatus = typeof UpdateDeviceModelStatusRequestStatus[keyof typeof UpdateDeviceModelStatusRequestStatus];


export const UpdateDeviceModelStatusRequestStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
