/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { Address } from './address.ts';
import type { MultiPolygon } from './multiPolygon.ts';

export interface UpdateBuildingRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  address?: Address;
  footprint: MultiPolygon;
  /** The location this building stands in; omit to detach it from the one it sits in now */
  locationId?: string;
  /** @minLength 1 */
  name: string;
  notes?: string;
}
