/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UpdateDeviceModelRequestMounting } from './updateDeviceModelRequestMounting.ts';

export interface UpdateDeviceModelRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** @minimum 1 */
  depthMm?: number;
  deviceTypeId: string;
  /** @minimum 1 */
  heightMm?: number;
  manufacturerId: string;
  mounting?: UpdateDeviceModelRequestMounting;
  /** @minLength 1 */
  name: string;
  notes?: string;
  partNumber?: string;
  /** Can be powered over Ethernet */
  poeIn?: boolean;
  /** Can power other devices over Ethernet */
  poeOut?: boolean;
  /**
     * Maximum power draw in watts
     * @minimum 1
     */
  powerWattsMax?: number;
  /** @minimum 1 */
  rackUnits?: number;
  /** @minimum 1 */
  widthMm?: number;
}
