/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UpdateUserRoleInputBodyRole } from './updateUserRoleInputBodyRole.ts';

export interface UpdateUserRoleInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /** Role to move the account to */
  role: UpdateUserRoleInputBodyRole;
}
