/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type UpdateBuildingStatusRequestStatus = typeof UpdateBuildingStatusRequestStatus[keyof typeof UpdateBuildingStatusRequestStatus];


export const UpdateBuildingStatusRequestStatus = {
  planned: 'planned',
  active: 'active',
  decommissioned: 'decommissioned',
  archived: 'archived',
} as const;
