/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface UpdateAccountInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * Current account password, confirming the change
     * @minLength 1
     */
  currentPassword: string;
  /** New account email address */
  email: string;
  /**
     * New account username
     * @minLength 3
     */
  username: string;
}
