/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UpdateDeviceModelStatusRequestStatus } from './updateDeviceModelStatusRequestStatus.ts';

export interface UpdateDeviceModelStatusRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  status: UpdateDeviceModelStatusRequestStatus;
}
