/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

/**
 * Role to move the account to
 */
export type UpdateUserRoleInputBodyRole = typeof UpdateUserRoleInputBodyRole[keyof typeof UpdateUserRoleInputBodyRole];


export const UpdateUserRoleInputBodyRole = {
  viewer: 'viewer',
  editor: 'editor',
  admin: 'admin',
} as const;
