/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UpdateLocationStatusRequestStatus } from './updateLocationStatusRequestStatus.ts';

export interface UpdateLocationStatusRequest {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  status: UpdateLocationStatusRequestStatus;
}
