/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface UpdatePasswordInputBody {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  /**
     * New account password
     * @minLength 8
     */
  newPassword: string;
  /**
     * Current account password
     * @minLength 1
     */
  oldPassword: string;
}
