/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type UploadAssetResourceType = typeof UploadAssetResourceType[keyof typeof UploadAssetResourceType];


export const UploadAssetResourceType = {
  location: 'location',
  building: 'building',
} as const;
