/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UploadAssetResourceType } from './uploadAssetResourceType.ts';

export type UploadAssetParams = {
title?: string;
resourceType?: UploadAssetResourceType;
resourceId?: string;
};
