/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  viewer: 'viewer',
  editor: 'editor',
  admin: 'admin',
} as const;
