/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */

export interface User {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  created_at: string;
  email: string;
  id: string;
  role: string;
  updated_at: string;
  username: string;
}
