/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import type { UserRole } from './userRole.ts';

export interface User {
  /** A URL to the JSON Schema for this object. */
  readonly $schema?: string;
  createdAt: string;
  email: string;
  id: string;
  permissions: string[];
  role: UserRole;
  updatedAt: string;
  username: string;
}
