/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BuildingResponse,
  CreateBuildingRequest,
  ErrorModel,
  ListBuildingsParams,
  UpdateBuildingRequest,
  UpdateBuildingStatusRequest
} from '../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listBuildingsResponse200 = {
  data: BuildingResponse[]
  status: 200
}

export type listBuildingsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listBuildingsResponseSuccess = (listBuildingsResponse200) & {
  headers: Headers;
};
export type listBuildingsResponseError = (listBuildingsResponseDefault) & {
  headers: Headers;
};

export type listBuildingsResponse = (listBuildingsResponseSuccess | listBuildingsResponseError)

export const getListBuildingsUrl = (params?: ListBuildingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/buildings?${stringifiedParams}` : `/api/buildings`
}

/**
 * @summary Returns all buildings
 */
export const listBuildings = async (params?: ListBuildingsParams, options?: RequestInit): Promise<listBuildingsResponse> => {

  const res = await fetch(getListBuildingsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listBuildingsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listBuildingsResponse
}





export const getListBuildingsQueryKey = (params?: ListBuildingsParams,) => {
    return [
    `/api/buildings`, ...(params ? [params] : [])
    ] as const;
    }


export const getListBuildingsQueryOptions = <TData = Awaited<ReturnType<typeof listBuildings>>, TError = ErrorModel>(params?: ListBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListBuildingsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listBuildings>>> = ({ signal }) => listBuildings(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListBuildingsQueryResult = NonNullable<Awaited<ReturnType<typeof listBuildings>>>
export type ListBuildingsQueryError = ErrorModel


export function useListBuildings<TData = Awaited<ReturnType<typeof listBuildings>>, TError = ErrorModel>(
 params: undefined |  ListBuildingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBuildings>>,
          TError,
          Awaited<ReturnType<typeof listBuildings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBuildings<TData = Awaited<ReturnType<typeof listBuildings>>, TError = ErrorModel>(
 params?: ListBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listBuildings>>,
          TError,
          Awaited<ReturnType<typeof listBuildings>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListBuildings<TData = Awaited<ReturnType<typeof listBuildings>>, TError = ErrorModel>(
 params?: ListBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all buildings
 */

export function useListBuildings<TData = Awaited<ReturnType<typeof listBuildings>>, TError = ErrorModel>(
 params?: ListBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listBuildings>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListBuildingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createBuildingResponse201 = {
  data: BuildingResponse
  status: 201
}

export type createBuildingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 201>
}

export type createBuildingResponseSuccess = (createBuildingResponse201) & {
  headers: Headers;
};
export type createBuildingResponseError = (createBuildingResponseDefault) & {
  headers: Headers;
};

export type createBuildingResponse = (createBuildingResponseSuccess | createBuildingResponseError)

export const getCreateBuildingUrl = () => {




  return `/api/buildings`
}

/**
 * @summary Creates a building
 */
export const createBuilding = async (createBuildingRequest: NonReadonly<CreateBuildingRequest>, options?: RequestInit): Promise<createBuildingResponse> => {

  const res = await fetch(getCreateBuildingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBuildingRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createBuildingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createBuildingResponse
}





export const getCreateBuildingMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBuilding>>, TError,{data: NonReadonly<CreateBuildingRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createBuilding>>, TError,{data: NonReadonly<CreateBuildingRequest>}, TContext> => {

const mutationKey = ['createBuilding'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBuilding>>, {data: NonReadonly<CreateBuildingRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createBuilding(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateBuildingMutationResult = NonNullable<Awaited<ReturnType<typeof createBuilding>>>
    export type CreateBuildingMutationBody = NonReadonly<CreateBuildingRequest>
    export type CreateBuildingMutationError = ErrorModel

    /**
 * @summary Creates a building
 */
export const useCreateBuilding = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBuilding>>, TError,{data: NonReadonly<CreateBuildingRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBuilding>>,
        TError,
        {data: NonReadonly<CreateBuildingRequest>},
        TContext
      > => {
      return useMutation(getCreateBuildingMutationOptions(options), queryClient);
    }
    export type deleteBuildingResponse204 = {
  data: void
  status: 204
}

export type deleteBuildingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteBuildingResponseSuccess = (deleteBuildingResponse204) & {
  headers: Headers;
};
export type deleteBuildingResponseError = (deleteBuildingResponseDefault) & {
  headers: Headers;
};

export type deleteBuildingResponse = (deleteBuildingResponseSuccess | deleteBuildingResponseError)

export const getDeleteBuildingUrl = (id: string,) => {




  return `/api/buildings/${id}`
}

/**
 * @summary Deletes the building with the provided id
 */
export const deleteBuilding = async (id: string, options?: RequestInit): Promise<deleteBuildingResponse> => {

  const res = await fetch(getDeleteBuildingUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteBuildingResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteBuildingResponse
}





export const getDeleteBuildingMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBuilding>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteBuilding>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteBuilding'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteBuilding>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteBuilding(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteBuildingMutationResult = NonNullable<Awaited<ReturnType<typeof deleteBuilding>>>

    export type DeleteBuildingMutationError = ErrorModel

    /**
 * @summary Deletes the building with the provided id
 */
export const useDeleteBuilding = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteBuilding>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteBuilding>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteBuildingMutationOptions(options), queryClient);
    }
    export type getBuildingResponse200 = {
  data: BuildingResponse
  status: 200
}

export type getBuildingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getBuildingResponseSuccess = (getBuildingResponse200) & {
  headers: Headers;
};
export type getBuildingResponseError = (getBuildingResponseDefault) & {
  headers: Headers;
};

export type getBuildingResponse = (getBuildingResponseSuccess | getBuildingResponseError)

export const getGetBuildingUrl = (id: string,) => {




  return `/api/buildings/${id}`
}

/**
 * @summary Returns building with the provided id
 */
export const getBuilding = async (id: string, options?: RequestInit): Promise<getBuildingResponse> => {

  const res = await fetch(getGetBuildingUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getBuildingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBuildingResponse
}





export const getGetBuildingQueryKey = (id: string,) => {
    return [
    `/api/buildings/${id}`
    ] as const;
    }


export const getGetBuildingQueryOptions = <TData = Awaited<ReturnType<typeof getBuilding>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBuildingQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBuilding>>> = ({ signal }) => getBuilding(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBuildingQueryResult = NonNullable<Awaited<ReturnType<typeof getBuilding>>>
export type GetBuildingQueryError = ErrorModel


export function useGetBuilding<TData = Awaited<ReturnType<typeof getBuilding>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuilding>>,
          TError,
          Awaited<ReturnType<typeof getBuilding>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuilding<TData = Awaited<ReturnType<typeof getBuilding>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuilding>>,
          TError,
          Awaited<ReturnType<typeof getBuilding>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuilding<TData = Awaited<ReturnType<typeof getBuilding>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns building with the provided id
 */

export function useGetBuilding<TData = Awaited<ReturnType<typeof getBuilding>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuilding>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBuildingQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateBuildingResponse200 = {
  data: BuildingResponse
  status: 200
}

export type updateBuildingResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateBuildingResponseSuccess = (updateBuildingResponse200) & {
  headers: Headers;
};
export type updateBuildingResponseError = (updateBuildingResponseDefault) & {
  headers: Headers;
};

export type updateBuildingResponse = (updateBuildingResponseSuccess | updateBuildingResponseError)

export const getUpdateBuildingUrl = (id: string,) => {




  return `/api/buildings/${id}`
}

/**
 * @summary Updates the building with the provided id
 */
export const updateBuilding = async (id: string,
    updateBuildingRequest: NonReadonly<UpdateBuildingRequest>, options?: RequestInit): Promise<updateBuildingResponse> => {

  const res = await fetch(getUpdateBuildingUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBuildingRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateBuildingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateBuildingResponse
}





export const getUpdateBuildingMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuilding>>, TError,{id: string;data: NonReadonly<UpdateBuildingRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateBuilding>>, TError,{id: string;data: NonReadonly<UpdateBuildingRequest>}, TContext> => {

const mutationKey = ['updateBuilding'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBuilding>>, {id: string;data: NonReadonly<UpdateBuildingRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBuilding(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBuildingMutationResult = NonNullable<Awaited<ReturnType<typeof updateBuilding>>>
    export type UpdateBuildingMutationBody = NonReadonly<UpdateBuildingRequest>
    export type UpdateBuildingMutationError = ErrorModel

    /**
 * @summary Updates the building with the provided id
 */
export const useUpdateBuilding = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuilding>>, TError,{id: string;data: NonReadonly<UpdateBuildingRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBuilding>>,
        TError,
        {id: string;data: NonReadonly<UpdateBuildingRequest>},
        TContext
      > => {
      return useMutation(getUpdateBuildingMutationOptions(options), queryClient);
    }
    export type updateBuildingStatusResponse200 = {
  data: BuildingResponse
  status: 200
}

export type updateBuildingStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateBuildingStatusResponseSuccess = (updateBuildingStatusResponse200) & {
  headers: Headers;
};
export type updateBuildingStatusResponseError = (updateBuildingStatusResponseDefault) & {
  headers: Headers;
};

export type updateBuildingStatusResponse = (updateBuildingStatusResponseSuccess | updateBuildingStatusResponseError)

export const getUpdateBuildingStatusUrl = (id: string,) => {




  return `/api/buildings/${id}/status`
}

/**
 * @summary Updates the building status of the building with provided id
 */
export const updateBuildingStatus = async (id: string,
    updateBuildingStatusRequest: NonReadonly<UpdateBuildingStatusRequest>, options?: RequestInit): Promise<updateBuildingStatusResponse> => {

  const res = await fetch(getUpdateBuildingStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBuildingStatusRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateBuildingStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateBuildingStatusResponse
}





export const getUpdateBuildingStatusMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuildingStatus>>, TError,{id: string;data: NonReadonly<UpdateBuildingStatusRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateBuildingStatus>>, TError,{id: string;data: NonReadonly<UpdateBuildingStatusRequest>}, TContext> => {

const mutationKey = ['updateBuildingStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBuildingStatus>>, {id: string;data: NonReadonly<UpdateBuildingStatusRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateBuildingStatus(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateBuildingStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateBuildingStatus>>>
    export type UpdateBuildingStatusMutationBody = NonReadonly<UpdateBuildingStatusRequest>
    export type UpdateBuildingStatusMutationError = ErrorModel

    /**
 * @summary Updates the building status of the building with provided id
 */
export const useUpdateBuildingStatus = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBuildingStatus>>, TError,{id: string;data: NonReadonly<UpdateBuildingStatusRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBuildingStatus>>,
        TError,
        {id: string;data: NonReadonly<UpdateBuildingStatusRequest>},
        TContext
      > => {
      return useMutation(getUpdateBuildingStatusMutationOptions(options), queryClient);
    }
