/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all locations
 */
export const ListLocationsQueryParams = zod.object({
  "status": zod.array(zod.enum(['planned', 'active', 'decommissioned', 'archived'])).optional().describe('Lifecycle statuses to include. Defaults to planned and active, which keeps decommissioned and archived locations off the map and out of the default lists without hiding them from a direct lookup.')
})

export const listLocationsResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const listLocationsResponseRepresentativePointCoordinatesMin = 2;
export const listLocationsResponseRepresentativePointCoordinatesMax = 3;



export const ListLocationsResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(listLocationsResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(listLocationsResponseRepresentativePointCoordinatesMin).max(listLocationsResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "representativePointManual": zod.boolean(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})
export const ListLocationsResponse = zod.array(ListLocationsResponseItem)

/**
 * @summary Creates a location
 */
export const createLocationBodyAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');

export const createLocationBodyRepresentativePointCoordinatesMin = 2;
export const createLocationBodyRepresentativePointCoordinatesMax = 3;



export const CreateLocationBody = zod.object({
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(createLocationBodyAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional().describe('The boundary of the location; omit for one whose extent nobody has established yet'),
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional().describe('The location this one sits inside; omit for a location that stands on its own'),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(createLocationBodyRepresentativePointCoordinatesMin).max(createLocationBodyRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived'])
})

export const createLocationResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const createLocationResponseRepresentativePointCoordinatesMin = 2;
export const createLocationResponseRepresentativePointCoordinatesMax = 3;



export const CreateLocationResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(createLocationResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(createLocationResponseRepresentativePointCoordinatesMin).max(createLocationResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "representativePointManual": zod.boolean(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Deletes the location with the provided id
 */
export const DeleteLocationParams = zod.object({
  "id": zod.string()
})

export const DeleteLocationResponse = zod.void()

/**
 * @summary Returns location with the provided id
 */
export const GetLocationParams = zod.object({
  "id": zod.string()
})

export const getLocationResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const getLocationResponseRepresentativePointCoordinatesMin = 2;
export const getLocationResponseRepresentativePointCoordinatesMax = 3;



export const GetLocationResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(getLocationResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(getLocationResponseRepresentativePointCoordinatesMin).max(getLocationResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "representativePointManual": zod.boolean(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Updates the location with the provided id
 */
export const UpdateLocationParams = zod.object({
  "id": zod.string()
})

export const updateLocationBodyAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');

export const updateLocationBodyRepresentativePointCoordinatesMin = 2;
export const updateLocationBodyRepresentativePointCoordinatesMax = 3;



export const UpdateLocationBody = zod.object({
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateLocationBodyAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional().describe('The boundary of the location; omit for one whose extent nobody has established yet'),
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional().describe('The location this one sits inside; omit to move it to the top level'),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateLocationBodyRepresentativePointCoordinatesMin).max(updateLocationBodyRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional()
})

export const updateLocationResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const updateLocationResponseRepresentativePointCoordinatesMin = 2;
export const updateLocationResponseRepresentativePointCoordinatesMax = 3;



export const UpdateLocationResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateLocationResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateLocationResponseRepresentativePointCoordinatesMin).max(updateLocationResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "representativePointManual": zod.boolean(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

/**
 * @summary Updates the location status of the location with provided id
 */
export const UpdateLocationStatusParams = zod.object({
  "id": zod.string()
})

export const UpdateLocationStatusBody = zod.object({
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived'])
})

export const updateLocationStatusResponseAddressCountryRegExp = new RegExp('^[A-Za-z]{2}$');
export const updateLocationStatusResponseRepresentativePointCoordinatesMin = 2;
export const updateLocationStatusResponseRepresentativePointCoordinatesMax = 3;



export const UpdateLocationStatusResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "address": zod.object({
  "city": zod.string().optional(),
  "country": zod.string().regex(updateLocationStatusResponseAddressCountryRegExp).optional().describe('ISO 3166-1 alpha-2 country code'),
  "street": zod.string().optional(),
  "zip": zod.string().optional().describe('Postal code, in whatever shape the country writes it')
}).optional(),
  "area": zod.object({
  "coordinates": zod.array(zod.array(zod.array(zod.array(zod.number())))).describe('An array of polygons, each an array of linear rings of [longitude, latitude] positions; a ring\'s first entry is its exterior boundary and the rest are holes'),
  "type": zod.enum(['MultiPolygon']).describe('GeoJSON geometry type')
}).optional(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "parentId": zod.string().optional(),
  "representativePoint": zod.object({
  "coordinates": zod.array(zod.number()).min(updateLocationStatusResponseRepresentativePointCoordinatesMin).max(updateLocationStatusResponseRepresentativePointCoordinatesMax).describe('A [longitude, latitude] position, optionally with elevation'),
  "type": zod.enum(['Point']).describe('GeoJSON geometry type')
}).optional(),
  "representativePointManual": zod.boolean(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true})
})

