/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateDeviceModelRequest,
  DeviceModelResponse,
  ErrorModel,
  ListDeviceModelsParams,
  UpdateDeviceModelRequest,
  UpdateDeviceModelStatusRequest
} from '../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listDeviceModelsResponse200 = {
  data: DeviceModelResponse[]
  status: 200
}

export type listDeviceModelsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listDeviceModelsResponseSuccess = (listDeviceModelsResponse200) & {
  headers: Headers;
};
export type listDeviceModelsResponseError = (listDeviceModelsResponseDefault) & {
  headers: Headers;
};

export type listDeviceModelsResponse = (listDeviceModelsResponseSuccess | listDeviceModelsResponseError)

export const getListDeviceModelsUrl = (params?: ListDeviceModelsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/device-models?${stringifiedParams}` : `/api/device-models`
}

/**
 * @summary Returns all device models, optionally narrowed to a device type or a manufacturer
 */
export const listDeviceModels = async (params?: ListDeviceModelsParams, options?: RequestInit): Promise<listDeviceModelsResponse> => {

  const res = await fetch(getListDeviceModelsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listDeviceModelsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listDeviceModelsResponse
}





export const getListDeviceModelsQueryKey = (params?: ListDeviceModelsParams,) => {
    return [
    `/api/device-models`, ...(params ? [params] : [])
    ] as const;
    }


export const getListDeviceModelsQueryOptions = <TData = Awaited<ReturnType<typeof listDeviceModels>>, TError = ErrorModel>(params?: ListDeviceModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDeviceModelsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDeviceModels>>> = ({ signal }) => listDeviceModels(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDeviceModelsQueryResult = NonNullable<Awaited<ReturnType<typeof listDeviceModels>>>
export type ListDeviceModelsQueryError = ErrorModel


export function useListDeviceModels<TData = Awaited<ReturnType<typeof listDeviceModels>>, TError = ErrorModel>(
 params: undefined |  ListDeviceModelsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeviceModels>>,
          TError,
          Awaited<ReturnType<typeof listDeviceModels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeviceModels<TData = Awaited<ReturnType<typeof listDeviceModels>>, TError = ErrorModel>(
 params?: ListDeviceModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDeviceModels>>,
          TError,
          Awaited<ReturnType<typeof listDeviceModels>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDeviceModels<TData = Awaited<ReturnType<typeof listDeviceModels>>, TError = ErrorModel>(
 params?: ListDeviceModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all device models, optionally narrowed to a device type or a manufacturer
 */

export function useListDeviceModels<TData = Awaited<ReturnType<typeof listDeviceModels>>, TError = ErrorModel>(
 params?: ListDeviceModelsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDeviceModels>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDeviceModelsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createDeviceModelResponse201 = {
  data: DeviceModelResponse
  status: 201
}

export type createDeviceModelResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 201>
}

export type createDeviceModelResponseSuccess = (createDeviceModelResponse201) & {
  headers: Headers;
};
export type createDeviceModelResponseError = (createDeviceModelResponseDefault) & {
  headers: Headers;
};

export type createDeviceModelResponse = (createDeviceModelResponseSuccess | createDeviceModelResponseError)

export const getCreateDeviceModelUrl = () => {




  return `/api/device-models`
}

/**
 * @summary Creates a device model
 */
export const createDeviceModel = async (createDeviceModelRequest: NonReadonly<CreateDeviceModelRequest>, options?: RequestInit): Promise<createDeviceModelResponse> => {

  const res = await fetch(getCreateDeviceModelUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createDeviceModelRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createDeviceModelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createDeviceModelResponse
}





export const getCreateDeviceModelMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeviceModel>>, TError,{data: NonReadonly<CreateDeviceModelRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createDeviceModel>>, TError,{data: NonReadonly<CreateDeviceModelRequest>}, TContext> => {

const mutationKey = ['createDeviceModel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDeviceModel>>, {data: NonReadonly<CreateDeviceModelRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createDeviceModel(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDeviceModelMutationResult = NonNullable<Awaited<ReturnType<typeof createDeviceModel>>>
    export type CreateDeviceModelMutationBody = NonReadonly<CreateDeviceModelRequest>
    export type CreateDeviceModelMutationError = ErrorModel

    /**
 * @summary Creates a device model
 */
export const useCreateDeviceModel = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDeviceModel>>, TError,{data: NonReadonly<CreateDeviceModelRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDeviceModel>>,
        TError,
        {data: NonReadonly<CreateDeviceModelRequest>},
        TContext
      > => {
      return useMutation(getCreateDeviceModelMutationOptions(options), queryClient);
    }
    export type deleteDeviceModelResponse204 = {
  data: void
  status: 204
}

export type deleteDeviceModelResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteDeviceModelResponseSuccess = (deleteDeviceModelResponse204) & {
  headers: Headers;
};
export type deleteDeviceModelResponseError = (deleteDeviceModelResponseDefault) & {
  headers: Headers;
};

export type deleteDeviceModelResponse = (deleteDeviceModelResponseSuccess | deleteDeviceModelResponseError)

export const getDeleteDeviceModelUrl = (id: string,) => {




  return `/api/device-models/${id}`
}

/**
 * @summary Deletes the device model with the provided id
 */
export const deleteDeviceModel = async (id: string, options?: RequestInit): Promise<deleteDeviceModelResponse> => {

  const res = await fetch(getDeleteDeviceModelUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteDeviceModelResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteDeviceModelResponse
}





export const getDeleteDeviceModelMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceModel>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceModel>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDeviceModel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDeviceModel>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDeviceModel(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDeviceModelMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDeviceModel>>>

    export type DeleteDeviceModelMutationError = ErrorModel

    /**
 * @summary Deletes the device model with the provided id
 */
export const useDeleteDeviceModel = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDeviceModel>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDeviceModel>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDeviceModelMutationOptions(options), queryClient);
    }
    export type getDeviceModelResponse200 = {
  data: DeviceModelResponse
  status: 200
}

export type getDeviceModelResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getDeviceModelResponseSuccess = (getDeviceModelResponse200) & {
  headers: Headers;
};
export type getDeviceModelResponseError = (getDeviceModelResponseDefault) & {
  headers: Headers;
};

export type getDeviceModelResponse = (getDeviceModelResponseSuccess | getDeviceModelResponseError)

export const getGetDeviceModelUrl = (id: string,) => {




  return `/api/device-models/${id}`
}

/**
 * @summary Returns the device model with the provided id
 */
export const getDeviceModel = async (id: string, options?: RequestInit): Promise<getDeviceModelResponse> => {

  const res = await fetch(getGetDeviceModelUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getDeviceModelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDeviceModelResponse
}





export const getGetDeviceModelQueryKey = (id: string,) => {
    return [
    `/api/device-models/${id}`
    ] as const;
    }


export const getGetDeviceModelQueryOptions = <TData = Awaited<ReturnType<typeof getDeviceModel>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDeviceModelQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDeviceModel>>> = ({ signal }) => getDeviceModel(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDeviceModelQueryResult = NonNullable<Awaited<ReturnType<typeof getDeviceModel>>>
export type GetDeviceModelQueryError = ErrorModel


export function useGetDeviceModel<TData = Awaited<ReturnType<typeof getDeviceModel>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceModel>>,
          TError,
          Awaited<ReturnType<typeof getDeviceModel>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeviceModel<TData = Awaited<ReturnType<typeof getDeviceModel>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDeviceModel>>,
          TError,
          Awaited<ReturnType<typeof getDeviceModel>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDeviceModel<TData = Awaited<ReturnType<typeof getDeviceModel>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the device model with the provided id
 */

export function useGetDeviceModel<TData = Awaited<ReturnType<typeof getDeviceModel>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDeviceModel>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDeviceModelQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateDeviceModelResponse200 = {
  data: DeviceModelResponse
  status: 200
}

export type updateDeviceModelResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateDeviceModelResponseSuccess = (updateDeviceModelResponse200) & {
  headers: Headers;
};
export type updateDeviceModelResponseError = (updateDeviceModelResponseDefault) & {
  headers: Headers;
};

export type updateDeviceModelResponse = (updateDeviceModelResponseSuccess | updateDeviceModelResponseError)

export const getUpdateDeviceModelUrl = (id: string,) => {




  return `/api/device-models/${id}`
}

/**
 * @summary Updates the device model with the provided id
 */
export const updateDeviceModel = async (id: string,
    updateDeviceModelRequest: NonReadonly<UpdateDeviceModelRequest>, options?: RequestInit): Promise<updateDeviceModelResponse> => {

  const res = await fetch(getUpdateDeviceModelUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDeviceModelRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateDeviceModelResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateDeviceModelResponse
}





export const getUpdateDeviceModelMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModel>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModel>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelRequest>}, TContext> => {

const mutationKey = ['updateDeviceModel'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDeviceModel>>, {id: string;data: NonReadonly<UpdateDeviceModelRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDeviceModel(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDeviceModelMutationResult = NonNullable<Awaited<ReturnType<typeof updateDeviceModel>>>
    export type UpdateDeviceModelMutationBody = NonReadonly<UpdateDeviceModelRequest>
    export type UpdateDeviceModelMutationError = ErrorModel

    /**
 * @summary Updates the device model with the provided id
 */
export const useUpdateDeviceModel = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModel>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDeviceModel>>,
        TError,
        {id: string;data: NonReadonly<UpdateDeviceModelRequest>},
        TContext
      > => {
      return useMutation(getUpdateDeviceModelMutationOptions(options), queryClient);
    }
    export type updateDeviceModelStatusResponse200 = {
  data: DeviceModelResponse
  status: 200
}

export type updateDeviceModelStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateDeviceModelStatusResponseSuccess = (updateDeviceModelStatusResponse200) & {
  headers: Headers;
};
export type updateDeviceModelStatusResponseError = (updateDeviceModelStatusResponseDefault) & {
  headers: Headers;
};

export type updateDeviceModelStatusResponse = (updateDeviceModelStatusResponseSuccess | updateDeviceModelStatusResponseError)

export const getUpdateDeviceModelStatusUrl = (id: string,) => {




  return `/api/device-models/${id}/status`
}

/**
 * @summary Updates the status of the device model with the provided id
 */
export const updateDeviceModelStatus = async (id: string,
    updateDeviceModelStatusRequest: NonReadonly<UpdateDeviceModelStatusRequest>, options?: RequestInit): Promise<updateDeviceModelStatusResponse> => {

  const res = await fetch(getUpdateDeviceModelStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateDeviceModelStatusRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateDeviceModelStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateDeviceModelStatusResponse
}





export const getUpdateDeviceModelStatusMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModelStatus>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelStatusRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModelStatus>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelStatusRequest>}, TContext> => {

const mutationKey = ['updateDeviceModelStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDeviceModelStatus>>, {id: string;data: NonReadonly<UpdateDeviceModelStatusRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDeviceModelStatus(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDeviceModelStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateDeviceModelStatus>>>
    export type UpdateDeviceModelStatusMutationBody = NonReadonly<UpdateDeviceModelStatusRequest>
    export type UpdateDeviceModelStatusMutationError = ErrorModel

    /**
 * @summary Updates the status of the device model with the provided id
 */
export const useUpdateDeviceModelStatus = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDeviceModelStatus>>, TError,{id: string;data: NonReadonly<UpdateDeviceModelStatusRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDeviceModelStatus>>,
        TError,
        {id: string;data: NonReadonly<UpdateDeviceModelStatusRequest>},
        TContext
      > => {
      return useMutation(getUpdateDeviceModelStatusMutationOptions(options), queryClient);
    }
