/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateLocationRequest,
  ErrorModel,
  ListLocationTreeParams,
  ListLocationsParams,
  LocationResponse,
  LocationTreeResponse,
  UpdateLocationRequest,
  UpdateLocationStatusRequest
} from '../model';


// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listLocationsResponse200 = {
  data: LocationResponse[]
  status: 200
}

export type listLocationsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listLocationsResponseSuccess = (listLocationsResponse200) & {
  headers: Headers;
};
export type listLocationsResponseError = (listLocationsResponseDefault) & {
  headers: Headers;
};

export type listLocationsResponse = (listLocationsResponseSuccess | listLocationsResponseError)

export const getListLocationsUrl = (params?: ListLocationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/locations?${stringifiedParams}` : `/api/locations`
}

/**
 * @summary Returns all locations
 */
export const listLocations = async (params?: ListLocationsParams, options?: RequestInit): Promise<listLocationsResponse> => {

  const res = await fetch(getListLocationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listLocationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listLocationsResponse
}





export const getListLocationsQueryKey = (params?: ListLocationsParams,) => {
    return [
    `/api/locations`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLocationsQueryOptions = <TData = Awaited<ReturnType<typeof listLocations>>, TError = ErrorModel>(params?: ListLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLocationsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLocations>>> = ({ signal }) => listLocations(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLocationsQueryResult = NonNullable<Awaited<ReturnType<typeof listLocations>>>
export type ListLocationsQueryError = ErrorModel


export function useListLocations<TData = Awaited<ReturnType<typeof listLocations>>, TError = ErrorModel>(
 params: undefined |  ListLocationsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLocations>>,
          TError,
          Awaited<ReturnType<typeof listLocations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLocations<TData = Awaited<ReturnType<typeof listLocations>>, TError = ErrorModel>(
 params?: ListLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLocations>>,
          TError,
          Awaited<ReturnType<typeof listLocations>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLocations<TData = Awaited<ReturnType<typeof listLocations>>, TError = ErrorModel>(
 params?: ListLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all locations
 */

export function useListLocations<TData = Awaited<ReturnType<typeof listLocations>>, TError = ErrorModel>(
 params?: ListLocationsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocations>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLocationsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createLocationResponse201 = {
  data: LocationResponse
  status: 201
}

export type createLocationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 201>
}

export type createLocationResponseSuccess = (createLocationResponse201) & {
  headers: Headers;
};
export type createLocationResponseError = (createLocationResponseDefault) & {
  headers: Headers;
};

export type createLocationResponse = (createLocationResponseSuccess | createLocationResponseError)

export const getCreateLocationUrl = () => {




  return `/api/locations`
}

/**
 * @summary Creates a location
 */
export const createLocation = async (createLocationRequest: NonReadonly<CreateLocationRequest>, options?: RequestInit): Promise<createLocationResponse> => {

  const res = await fetch(getCreateLocationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createLocationRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createLocationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createLocationResponse
}





export const getCreateLocationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLocation>>, TError,{data: NonReadonly<CreateLocationRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createLocation>>, TError,{data: NonReadonly<CreateLocationRequest>}, TContext> => {

const mutationKey = ['createLocation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createLocation>>, {data: NonReadonly<CreateLocationRequest>}> = (props) => {
          const {data} = props ?? {};

          return  createLocation(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateLocationMutationResult = NonNullable<Awaited<ReturnType<typeof createLocation>>>
    export type CreateLocationMutationBody = NonReadonly<CreateLocationRequest>
    export type CreateLocationMutationError = ErrorModel

    /**
 * @summary Creates a location
 */
export const useCreateLocation = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createLocation>>, TError,{data: NonReadonly<CreateLocationRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createLocation>>,
        TError,
        {data: NonReadonly<CreateLocationRequest>},
        TContext
      > => {
      return useMutation(getCreateLocationMutationOptions(options), queryClient);
    }
    export type listLocationTreeResponse200 = {
  data: LocationTreeResponse[]
  status: 200
}

export type listLocationTreeResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listLocationTreeResponseSuccess = (listLocationTreeResponse200) & {
  headers: Headers;
};
export type listLocationTreeResponseError = (listLocationTreeResponseDefault) & {
  headers: Headers;
};

export type listLocationTreeResponse = (listLocationTreeResponseSuccess | listLocationTreeResponseError)

export const getListLocationTreeUrl = (params?: ListLocationTreeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/locations/tree?${stringifiedParams}` : `/api/locations/tree`
}

/**
 * @summary Returns all locations in tree order, with their depth
 */
export const listLocationTree = async (params?: ListLocationTreeParams, options?: RequestInit): Promise<listLocationTreeResponse> => {

  const res = await fetch(getListLocationTreeUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listLocationTreeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listLocationTreeResponse
}





export const getListLocationTreeQueryKey = (params?: ListLocationTreeParams,) => {
    return [
    `/api/locations/tree`, ...(params ? [params] : [])
    ] as const;
    }


export const getListLocationTreeQueryOptions = <TData = Awaited<ReturnType<typeof listLocationTree>>, TError = ErrorModel>(params?: ListLocationTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListLocationTreeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listLocationTree>>> = ({ signal }) => listLocationTree(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListLocationTreeQueryResult = NonNullable<Awaited<ReturnType<typeof listLocationTree>>>
export type ListLocationTreeQueryError = ErrorModel


export function useListLocationTree<TData = Awaited<ReturnType<typeof listLocationTree>>, TError = ErrorModel>(
 params: undefined |  ListLocationTreeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLocationTree>>,
          TError,
          Awaited<ReturnType<typeof listLocationTree>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLocationTree<TData = Awaited<ReturnType<typeof listLocationTree>>, TError = ErrorModel>(
 params?: ListLocationTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLocationTree>>,
          TError,
          Awaited<ReturnType<typeof listLocationTree>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListLocationTree<TData = Awaited<ReturnType<typeof listLocationTree>>, TError = ErrorModel>(
 params?: ListLocationTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns all locations in tree order, with their depth
 */

export function useListLocationTree<TData = Awaited<ReturnType<typeof listLocationTree>>, TError = ErrorModel>(
 params?: ListLocationTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listLocationTree>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListLocationTreeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteLocationResponse204 = {
  data: void
  status: 204
}

export type deleteLocationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteLocationResponseSuccess = (deleteLocationResponse204) & {
  headers: Headers;
};
export type deleteLocationResponseError = (deleteLocationResponseDefault) & {
  headers: Headers;
};

export type deleteLocationResponse = (deleteLocationResponseSuccess | deleteLocationResponseError)

export const getDeleteLocationUrl = (id: string,) => {




  return `/api/locations/${id}`
}

/**
 * @summary Soft deletes the location with the provided id
 */
export const deleteLocation = async (id: string, options?: RequestInit): Promise<deleteLocationResponse> => {

  const res = await fetch(getDeleteLocationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteLocationResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteLocationResponse
}





export const getDeleteLocationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteLocation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLocation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteLocation(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLocationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLocation>>>

    export type DeleteLocationMutationError = ErrorModel

    /**
 * @summary Soft deletes the location with the provided id
 */
export const useDeleteLocation = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLocation>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLocation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteLocationMutationOptions(options), queryClient);
    }
    export type getLocationResponse200 = {
  data: LocationResponse
  status: 200
}

export type getLocationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getLocationResponseSuccess = (getLocationResponse200) & {
  headers: Headers;
};
export type getLocationResponseError = (getLocationResponseDefault) & {
  headers: Headers;
};

export type getLocationResponse = (getLocationResponseSuccess | getLocationResponseError)

export const getGetLocationUrl = (id: string,) => {




  return `/api/locations/${id}`
}

/**
 * @summary Returns location with the provided id
 */
export const getLocation = async (id: string, options?: RequestInit): Promise<getLocationResponse> => {

  const res = await fetch(getGetLocationUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getLocationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLocationResponse
}





export const getGetLocationQueryKey = (id: string,) => {
    return [
    `/api/locations/${id}`
    ] as const;
    }


export const getGetLocationQueryOptions = <TData = Awaited<ReturnType<typeof getLocation>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLocationQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLocation>>> = ({ signal }) => getLocation(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLocationQueryResult = NonNullable<Awaited<ReturnType<typeof getLocation>>>
export type GetLocationQueryError = ErrorModel


export function useGetLocation<TData = Awaited<ReturnType<typeof getLocation>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocation>>,
          TError,
          Awaited<ReturnType<typeof getLocation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocation<TData = Awaited<ReturnType<typeof getLocation>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLocation>>,
          TError,
          Awaited<ReturnType<typeof getLocation>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLocation<TData = Awaited<ReturnType<typeof getLocation>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns location with the provided id
 */

export function useGetLocation<TData = Awaited<ReturnType<typeof getLocation>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLocation>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLocationQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type updateLocationResponse200 = {
  data: LocationResponse
  status: 200
}

export type updateLocationResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateLocationResponseSuccess = (updateLocationResponse200) & {
  headers: Headers;
};
export type updateLocationResponseError = (updateLocationResponseDefault) & {
  headers: Headers;
};

export type updateLocationResponse = (updateLocationResponseSuccess | updateLocationResponseError)

export const getUpdateLocationUrl = (id: string,) => {




  return `/api/locations/${id}`
}

/**
 * @summary Updates the location with the provided id
 */
export const updateLocation = async (id: string,
    updateLocationRequest: NonReadonly<UpdateLocationRequest>, options?: RequestInit): Promise<updateLocationResponse> => {

  const res = await fetch(getUpdateLocationUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLocationRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateLocationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateLocationResponse
}





export const getUpdateLocationMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLocation>>, TError,{id: string;data: NonReadonly<UpdateLocationRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateLocation>>, TError,{id: string;data: NonReadonly<UpdateLocationRequest>}, TContext> => {

const mutationKey = ['updateLocation'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLocation>>, {id: string;data: NonReadonly<UpdateLocationRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLocation(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLocationMutationResult = NonNullable<Awaited<ReturnType<typeof updateLocation>>>
    export type UpdateLocationMutationBody = NonReadonly<UpdateLocationRequest>
    export type UpdateLocationMutationError = ErrorModel

    /**
 * @summary Updates the location with the provided id
 */
export const useUpdateLocation = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLocation>>, TError,{id: string;data: NonReadonly<UpdateLocationRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLocation>>,
        TError,
        {id: string;data: NonReadonly<UpdateLocationRequest>},
        TContext
      > => {
      return useMutation(getUpdateLocationMutationOptions(options), queryClient);
    }
    export type updateLocationStatusResponse200 = {
  data: LocationResponse
  status: 200
}

export type updateLocationStatusResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type updateLocationStatusResponseSuccess = (updateLocationStatusResponse200) & {
  headers: Headers;
};
export type updateLocationStatusResponseError = (updateLocationStatusResponseDefault) & {
  headers: Headers;
};

export type updateLocationStatusResponse = (updateLocationStatusResponseSuccess | updateLocationStatusResponseError)

export const getUpdateLocationStatusUrl = (id: string,) => {




  return `/api/locations/${id}/status`
}

/**
 * @summary Updates the location status of the location with provided id
 */
export const updateLocationStatus = async (id: string,
    updateLocationStatusRequest: NonReadonly<UpdateLocationStatusRequest>, options?: RequestInit): Promise<updateLocationStatusResponse> => {

  const res = await fetch(getUpdateLocationStatusUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateLocationStatusRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateLocationStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateLocationStatusResponse
}





export const getUpdateLocationStatusMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLocationStatus>>, TError,{id: string;data: NonReadonly<UpdateLocationStatusRequest>}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateLocationStatus>>, TError,{id: string;data: NonReadonly<UpdateLocationStatusRequest>}, TContext> => {

const mutationKey = ['updateLocationStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateLocationStatus>>, {id: string;data: NonReadonly<UpdateLocationStatusRequest>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateLocationStatus(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateLocationStatusMutationResult = NonNullable<Awaited<ReturnType<typeof updateLocationStatus>>>
    export type UpdateLocationStatusMutationBody = NonReadonly<UpdateLocationStatusRequest>
    export type UpdateLocationStatusMutationError = ErrorModel

    /**
 * @summary Updates the location status of the location with provided id
 */
export const useUpdateLocationStatus = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateLocationStatus>>, TError,{id: string;data: NonReadonly<UpdateLocationStatusRequest>}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateLocationStatus>>,
        TError,
        {id: string;data: NonReadonly<UpdateLocationStatusRequest>},
        TContext
      > => {
      return useMutation(getUpdateLocationStatusMutationOptions(options), queryClient);
    }
