/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all device types.
 */
export const ListDeviceTypesResponseItem = zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
})
export const ListDeviceTypesResponse = zod.array(ListDeviceTypesResponseItem)

