/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/_map'
import { Route as AuthenticatedNavRouteImport } from './routes/_authenticated/_nav'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedMapIndexRouteImport } from './routes/_authenticated/_map/index'
import { Route as AuthenticatedMapBuildingsRouteImport } from './routes/_authenticated/_map/buildings'
import { Route as AuthenticatedMapLocationsRouteImport } from './routes/_authenticated/_map/locations'
import { Route as AuthenticatedMapBuildingsBuildingIdRouteImport } from './routes/_authenticated/_map/buildings.$buildingId'
import { Route as AuthenticatedMapBuildingsNewRouteImport } from './routes/_authenticated/_map/buildings.new'
import { Route as AuthenticatedMapLocationsLocationIdRouteImport } from './routes/_authenticated/_map/locations.$locationId'
import { Route as AuthenticatedMapLocationsNewRouteImport } from './routes/_authenticated/_map/locations.new'
import { Route as AuthenticatedNavAuthAccountRouteImport } from './routes/_authenticated/_nav/auth.account'
import { Route as AuthenticatedNavBuildingsIndexRouteImport } from './routes/_authenticated/_nav/buildings.index'
import { Route as AuthenticatedNavLocationsIndexRouteImport } from './routes/_authenticated/_nav/locations.index'
import { Route as AuthenticatedMapBuildingsBuildingIdEditRouteImport } from './routes/_authenticated/_map/buildings.$buildingId_.edit'
import { Route as AuthenticatedMapLocationsLocationIdEditRouteImport } from './routes/_authenticated/_map/locations.$locationId_.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/_map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNavRoute = AuthenticatedNavRouteImport.update({
  id: '/_nav',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapIndexRoute = AuthenticatedMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMapRoute,
} as any)
const AuthenticatedMapBuildingsRoute =
  AuthenticatedMapBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => AuthenticatedMapRoute,
  } as any)
const AuthenticatedMapLocationsRoute =
  AuthenticatedMapLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedMapRoute,
  } as any)
const AuthenticatedMapBuildingsBuildingIdRoute =
  AuthenticatedMapBuildingsBuildingIdRouteImport.update({
    id: '/$buildingId',
    path: '/$buildingId',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)
const AuthenticatedMapBuildingsNewRoute =
  AuthenticatedMapBuildingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)
const AuthenticatedMapLocationsLocationIdRoute =
  AuthenticatedMapLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => AuthenticatedMapLocationsRoute,
  } as any)
const AuthenticatedMapLocationsNewRoute =
  AuthenticatedMapLocationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMapLocationsRoute,
  } as any)
const AuthenticatedNavAuthAccountRoute =
  AuthenticatedNavAuthAccountRouteImport.update({
    id: '/auth/account',
    path: '/auth/account',
    getParentRoute: () => AuthenticatedNavRoute,
  } as any)
const AuthenticatedNavBuildingsIndexRoute =
  AuthenticatedNavBuildingsIndexRouteImport.update({
    id: '/buildings/',
    path: '/buildings/',
    getParentRoute: () => AuthenticatedNavRoute,
  } as any)
const AuthenticatedNavLocationsIndexRoute =
  AuthenticatedNavLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedNavRoute,
  } as any)
const AuthenticatedMapBuildingsBuildingIdEditRoute =
  AuthenticatedMapBuildingsBuildingIdEditRouteImport.update({
    id: '/$buildingId_/edit',
    path: '/$buildingId/edit',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)
const AuthenticatedMapLocationsLocationIdEditRoute =
  AuthenticatedMapLocationsLocationIdEditRouteImport.update({
    id: '/$locationId_/edit',
    path: '/$locationId/edit',
    getParentRoute: () => AuthenticatedMapLocationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMapIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/buildings': typeof AuthenticatedMapBuildingsRouteWithChildren
  '/locations': typeof AuthenticatedMapLocationsRouteWithChildren
  '/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/locations/$locationId': typeof AuthenticatedMapLocationsLocationIdRoute
  '/locations/new': typeof AuthenticatedMapLocationsNewRoute
  '/auth/account': typeof AuthenticatedNavAuthAccountRoute
  '/buildings/': typeof AuthenticatedNavBuildingsIndexRoute
  '/locations/': typeof AuthenticatedNavLocationsIndexRoute
  '/buildings/$buildingId/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
  '/locations/$locationId/edit': typeof AuthenticatedMapLocationsLocationIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMapIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/buildings': typeof AuthenticatedNavBuildingsIndexRoute
  '/locations': typeof AuthenticatedNavLocationsIndexRoute
  '/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/locations/$locationId': typeof AuthenticatedMapLocationsLocationIdRoute
  '/locations/new': typeof AuthenticatedMapLocationsNewRoute
  '/auth/account': typeof AuthenticatedNavAuthAccountRoute
  '/buildings/$buildingId/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
  '/locations/$locationId/edit': typeof AuthenticatedMapLocationsLocationIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_map': typeof AuthenticatedMapRouteWithChildren
  '/_authenticated/_nav': typeof AuthenticatedNavRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/_map/buildings': typeof AuthenticatedMapBuildingsRouteWithChildren
  '/_authenticated/_map/locations': typeof AuthenticatedMapLocationsRouteWithChildren
  '/_authenticated/_map/': typeof AuthenticatedMapIndexRoute
  '/_authenticated/_map/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/_authenticated/_map/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/_authenticated/_map/locations/$locationId': typeof AuthenticatedMapLocationsLocationIdRoute
  '/_authenticated/_map/locations/new': typeof AuthenticatedMapLocationsNewRoute
  '/_authenticated/_nav/auth/account': typeof AuthenticatedNavAuthAccountRoute
  '/_authenticated/_nav/buildings/': typeof AuthenticatedNavBuildingsIndexRoute
  '/_authenticated/_nav/locations/': typeof AuthenticatedNavLocationsIndexRoute
  '/_authenticated/_map/buildings/$buildingId_/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
  '/_authenticated/_map/locations/$locationId_/edit': typeof AuthenticatedMapLocationsLocationIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/buildings'
    | '/locations'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/auth/account'
    | '/buildings/'
    | '/locations/'
    | '/buildings/$buildingId/edit'
    | '/locations/$locationId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/buildings'
    | '/locations'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/auth/account'
    | '/buildings/$buildingId/edit'
    | '/locations/$locationId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_map'
    | '/_authenticated/_nav'
    | '/auth/login'
    | '/_authenticated/_map/buildings'
    | '/_authenticated/_map/locations'
    | '/_authenticated/_map/'
    | '/_authenticated/_map/buildings/$buildingId'
    | '/_authenticated/_map/buildings/new'
    | '/_authenticated/_map/locations/$locationId'
    | '/_authenticated/_map/locations/new'
    | '/_authenticated/_nav/auth/account'
    | '/_authenticated/_nav/buildings/'
    | '/_authenticated/_nav/locations/'
    | '/_authenticated/_map/buildings/$buildingId_/edit'
    | '/_authenticated/_map/locations/$locationId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_map': {
      id: '/_authenticated/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_nav': {
      id: '/_authenticated/_nav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedNavRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_map/': {
      id: '/_authenticated/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMapIndexRouteImport
      parentRoute: typeof AuthenticatedMapRoute
    }
    '/_authenticated/_map/buildings': {
      id: '/_authenticated/_map/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedMapBuildingsRouteImport
      parentRoute: typeof AuthenticatedMapRoute
    }
    '/_authenticated/_map/locations': {
      id: '/_authenticated/_map/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedMapLocationsRouteImport
      parentRoute: typeof AuthenticatedMapRoute
    }
    '/_authenticated/_map/buildings/$buildingId': {
      id: '/_authenticated/_map/buildings/$buildingId'
      path: '/$buildingId'
      fullPath: '/buildings/$buildingId'
      preLoaderRoute: typeof AuthenticatedMapBuildingsBuildingIdRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
    '/_authenticated/_map/buildings/new': {
      id: '/_authenticated/_map/buildings/new'
      path: '/new'
      fullPath: '/buildings/new'
      preLoaderRoute: typeof AuthenticatedMapBuildingsNewRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
    '/_authenticated/_map/locations/$locationId': {
      id: '/_authenticated/_map/locations/$locationId'
      path: '/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedMapLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedMapLocationsRoute
    }
    '/_authenticated/_map/locations/new': {
      id: '/_authenticated/_map/locations/new'
      path: '/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof AuthenticatedMapLocationsNewRouteImport
      parentRoute: typeof AuthenticatedMapLocationsRoute
    }
    '/_authenticated/_nav/auth/account': {
      id: '/_authenticated/_nav/auth/account'
      path: '/auth/account'
      fullPath: '/auth/account'
      preLoaderRoute: typeof AuthenticatedNavAuthAccountRouteImport
      parentRoute: typeof AuthenticatedNavRoute
    }
    '/_authenticated/_nav/buildings/': {
      id: '/_authenticated/_nav/buildings/'
      path: '/buildings'
      fullPath: '/buildings/'
      preLoaderRoute: typeof AuthenticatedNavBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedNavRoute
    }
    '/_authenticated/_nav/locations/': {
      id: '/_authenticated/_nav/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedNavLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedNavRoute
    }
    '/_authenticated/_map/buildings/$buildingId_/edit': {
      id: '/_authenticated/_map/buildings/$buildingId_/edit'
      path: '/$buildingId/edit'
      fullPath: '/buildings/$buildingId/edit'
      preLoaderRoute: typeof AuthenticatedMapBuildingsBuildingIdEditRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
    '/_authenticated/_map/locations/$locationId_/edit': {
      id: '/_authenticated/_map/locations/$locationId_/edit'
      path: '/$locationId/edit'
      fullPath: '/locations/$locationId/edit'
      preLoaderRoute: typeof AuthenticatedMapLocationsLocationIdEditRouteImport
      parentRoute: typeof AuthenticatedMapLocationsRoute
    }
  }
}

interface AuthenticatedMapBuildingsRouteChildren {
  AuthenticatedMapBuildingsBuildingIdRoute: typeof AuthenticatedMapBuildingsBuildingIdRoute
  AuthenticatedMapBuildingsNewRoute: typeof AuthenticatedMapBuildingsNewRoute
  AuthenticatedMapBuildingsBuildingIdEditRoute: typeof AuthenticatedMapBuildingsBuildingIdEditRoute
}

const AuthenticatedMapBuildingsRouteChildren: AuthenticatedMapBuildingsRouteChildren =
  {
    AuthenticatedMapBuildingsBuildingIdRoute:
      AuthenticatedMapBuildingsBuildingIdRoute,
    AuthenticatedMapBuildingsNewRoute: AuthenticatedMapBuildingsNewRoute,
    AuthenticatedMapBuildingsBuildingIdEditRoute:
      AuthenticatedMapBuildingsBuildingIdEditRoute,
  }

const AuthenticatedMapBuildingsRouteWithChildren =
  AuthenticatedMapBuildingsRoute._addFileChildren(
    AuthenticatedMapBuildingsRouteChildren,
  )

interface AuthenticatedMapLocationsRouteChildren {
  AuthenticatedMapLocationsLocationIdRoute: typeof AuthenticatedMapLocationsLocationIdRoute
  AuthenticatedMapLocationsNewRoute: typeof AuthenticatedMapLocationsNewRoute
  AuthenticatedMapLocationsLocationIdEditRoute: typeof AuthenticatedMapLocationsLocationIdEditRoute
}

const AuthenticatedMapLocationsRouteChildren: AuthenticatedMapLocationsRouteChildren =
  {
    AuthenticatedMapLocationsLocationIdRoute:
      AuthenticatedMapLocationsLocationIdRoute,
    AuthenticatedMapLocationsNewRoute: AuthenticatedMapLocationsNewRoute,
    AuthenticatedMapLocationsLocationIdEditRoute:
      AuthenticatedMapLocationsLocationIdEditRoute,
  }

const AuthenticatedMapLocationsRouteWithChildren =
  AuthenticatedMapLocationsRoute._addFileChildren(
    AuthenticatedMapLocationsRouteChildren,
  )

interface AuthenticatedMapRouteChildren {
  AuthenticatedMapBuildingsRoute: typeof AuthenticatedMapBuildingsRouteWithChildren
  AuthenticatedMapLocationsRoute: typeof AuthenticatedMapLocationsRouteWithChildren
  AuthenticatedMapIndexRoute: typeof AuthenticatedMapIndexRoute
}

const AuthenticatedMapRouteChildren: AuthenticatedMapRouteChildren = {
  AuthenticatedMapBuildingsRoute: AuthenticatedMapBuildingsRouteWithChildren,
  AuthenticatedMapLocationsRoute: AuthenticatedMapLocationsRouteWithChildren,
  AuthenticatedMapIndexRoute: AuthenticatedMapIndexRoute,
}

const AuthenticatedMapRouteWithChildren =
  AuthenticatedMapRoute._addFileChildren(AuthenticatedMapRouteChildren)

interface AuthenticatedNavRouteChildren {
  AuthenticatedNavAuthAccountRoute: typeof AuthenticatedNavAuthAccountRoute
  AuthenticatedNavBuildingsIndexRoute: typeof AuthenticatedNavBuildingsIndexRoute
  AuthenticatedNavLocationsIndexRoute: typeof AuthenticatedNavLocationsIndexRoute
}

const AuthenticatedNavRouteChildren: AuthenticatedNavRouteChildren = {
  AuthenticatedNavAuthAccountRoute: AuthenticatedNavAuthAccountRoute,
  AuthenticatedNavBuildingsIndexRoute: AuthenticatedNavBuildingsIndexRoute,
  AuthenticatedNavLocationsIndexRoute: AuthenticatedNavLocationsIndexRoute,
}

const AuthenticatedNavRouteWithChildren =
  AuthenticatedNavRoute._addFileChildren(AuthenticatedNavRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMapRoute: typeof AuthenticatedMapRouteWithChildren
  AuthenticatedNavRoute: typeof AuthenticatedNavRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMapRoute: AuthenticatedMapRouteWithChildren,
  AuthenticatedNavRoute: AuthenticatedNavRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
