/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/_map'
import { Route as AuthenticatedNavRouteImport } from './routes/_authenticated/_nav'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedMapIndexRouteImport } from './routes/_authenticated/_map/index'
import { Route as AuthenticatedMapBuildingsRouteImport } from './routes/_authenticated/_map/buildings'
import { Route as AuthenticatedAuthAccountRouteImport } from './routes/_authenticated/auth/account'
import { Route as AuthenticatedMapBuildingsBuildingIdRouteImport } from './routes/_authenticated/_map/buildings.$buildingId'
import { Route as AuthenticatedMapBuildingsNewRouteImport } from './routes/_authenticated/_map/buildings.new'
import { Route as AuthenticatedNavBuildingsIndexRouteImport } from './routes/_authenticated/_nav/buildings.index'
import { Route as AuthenticatedMapBuildingsBuildingIdEditRouteImport } from './routes/_authenticated/_map/buildings.$buildingId_.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/_map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNavRoute = AuthenticatedNavRouteImport.update({
  id: '/_nav',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMapIndexRoute = AuthenticatedMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedMapRoute,
} as any)
const AuthenticatedMapBuildingsRoute =
  AuthenticatedMapBuildingsRouteImport.update({
    id: '/buildings',
    path: '/buildings',
    getParentRoute: () => AuthenticatedMapRoute,
  } as any)
const AuthenticatedAuthAccountRoute =
  AuthenticatedAuthAccountRouteImport.update({
    id: '/auth/account',
    path: '/auth/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapBuildingsBuildingIdRoute =
  AuthenticatedMapBuildingsBuildingIdRouteImport.update({
    id: '/$buildingId',
    path: '/$buildingId',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)
const AuthenticatedMapBuildingsNewRoute =
  AuthenticatedMapBuildingsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)
const AuthenticatedNavBuildingsIndexRoute =
  AuthenticatedNavBuildingsIndexRouteImport.update({
    id: '/buildings/',
    path: '/buildings/',
    getParentRoute: () => AuthenticatedNavRoute,
  } as any)
const AuthenticatedMapBuildingsBuildingIdEditRoute =
  AuthenticatedMapBuildingsBuildingIdEditRouteImport.update({
    id: '/$buildingId_/edit',
    path: '/$buildingId/edit',
    getParentRoute: () => AuthenticatedMapBuildingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedMapIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/buildings': typeof AuthenticatedMapBuildingsRouteWithChildren
  '/auth/account': typeof AuthenticatedAuthAccountRoute
  '/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/buildings/': typeof AuthenticatedNavBuildingsIndexRoute
  '/buildings/$buildingId/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedMapIndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/buildings': typeof AuthenticatedNavBuildingsIndexRoute
  '/auth/account': typeof AuthenticatedAuthAccountRoute
  '/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/buildings/$buildingId/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_map': typeof AuthenticatedMapRouteWithChildren
  '/_authenticated/_nav': typeof AuthenticatedNavRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/_map/buildings': typeof AuthenticatedMapBuildingsRouteWithChildren
  '/_authenticated/auth/account': typeof AuthenticatedAuthAccountRoute
  '/_authenticated/_map/': typeof AuthenticatedMapIndexRoute
  '/_authenticated/_map/buildings/$buildingId': typeof AuthenticatedMapBuildingsBuildingIdRoute
  '/_authenticated/_map/buildings/new': typeof AuthenticatedMapBuildingsNewRoute
  '/_authenticated/_nav/buildings/': typeof AuthenticatedNavBuildingsIndexRoute
  '/_authenticated/_map/buildings/$buildingId_/edit': typeof AuthenticatedMapBuildingsBuildingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/buildings'
    | '/auth/account'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/buildings/'
    | '/buildings/$buildingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/buildings'
    | '/auth/account'
    | '/buildings/$buildingId'
    | '/buildings/new'
    | '/buildings/$buildingId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/_map'
    | '/_authenticated/_nav'
    | '/auth/login'
    | '/_authenticated/_map/buildings'
    | '/_authenticated/auth/account'
    | '/_authenticated/_map/'
    | '/_authenticated/_map/buildings/$buildingId'
    | '/_authenticated/_map/buildings/new'
    | '/_authenticated/_nav/buildings/'
    | '/_authenticated/_map/buildings/$buildingId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_map': {
      id: '/_authenticated/_map'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_nav': {
      id: '/_authenticated/_nav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedNavRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_map/': {
      id: '/_authenticated/_map/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedMapIndexRouteImport
      parentRoute: typeof AuthenticatedMapRoute
    }
    '/_authenticated/_map/buildings': {
      id: '/_authenticated/_map/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedMapBuildingsRouteImport
      parentRoute: typeof AuthenticatedMapRoute
    }
    '/_authenticated/auth/account': {
      id: '/_authenticated/auth/account'
      path: '/auth/account'
      fullPath: '/auth/account'
      preLoaderRoute: typeof AuthenticatedAuthAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_map/buildings/$buildingId': {
      id: '/_authenticated/_map/buildings/$buildingId'
      path: '/$buildingId'
      fullPath: '/buildings/$buildingId'
      preLoaderRoute: typeof AuthenticatedMapBuildingsBuildingIdRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
    '/_authenticated/_map/buildings/new': {
      id: '/_authenticated/_map/buildings/new'
      path: '/new'
      fullPath: '/buildings/new'
      preLoaderRoute: typeof AuthenticatedMapBuildingsNewRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
    '/_authenticated/_nav/buildings/': {
      id: '/_authenticated/_nav/buildings/'
      path: '/buildings'
      fullPath: '/buildings/'
      preLoaderRoute: typeof AuthenticatedNavBuildingsIndexRouteImport
      parentRoute: typeof AuthenticatedNavRoute
    }
    '/_authenticated/_map/buildings/$buildingId_/edit': {
      id: '/_authenticated/_map/buildings/$buildingId_/edit'
      path: '/$buildingId/edit'
      fullPath: '/buildings/$buildingId/edit'
      preLoaderRoute: typeof AuthenticatedMapBuildingsBuildingIdEditRouteImport
      parentRoute: typeof AuthenticatedMapBuildingsRoute
    }
  }
}

interface AuthenticatedMapBuildingsRouteChildren {
  AuthenticatedMapBuildingsBuildingIdRoute: typeof AuthenticatedMapBuildingsBuildingIdRoute
  AuthenticatedMapBuildingsNewRoute: typeof AuthenticatedMapBuildingsNewRoute
  AuthenticatedMapBuildingsBuildingIdEditRoute: typeof AuthenticatedMapBuildingsBuildingIdEditRoute
}

const AuthenticatedMapBuildingsRouteChildren: AuthenticatedMapBuildingsRouteChildren =
  {
    AuthenticatedMapBuildingsBuildingIdRoute:
      AuthenticatedMapBuildingsBuildingIdRoute,
    AuthenticatedMapBuildingsNewRoute: AuthenticatedMapBuildingsNewRoute,
    AuthenticatedMapBuildingsBuildingIdEditRoute:
      AuthenticatedMapBuildingsBuildingIdEditRoute,
  }

const AuthenticatedMapBuildingsRouteWithChildren =
  AuthenticatedMapBuildingsRoute._addFileChildren(
    AuthenticatedMapBuildingsRouteChildren,
  )

interface AuthenticatedMapRouteChildren {
  AuthenticatedMapBuildingsRoute: typeof AuthenticatedMapBuildingsRouteWithChildren
  AuthenticatedMapIndexRoute: typeof AuthenticatedMapIndexRoute
}

const AuthenticatedMapRouteChildren: AuthenticatedMapRouteChildren = {
  AuthenticatedMapBuildingsRoute: AuthenticatedMapBuildingsRouteWithChildren,
  AuthenticatedMapIndexRoute: AuthenticatedMapIndexRoute,
}

const AuthenticatedMapRouteWithChildren =
  AuthenticatedMapRoute._addFileChildren(AuthenticatedMapRouteChildren)

interface AuthenticatedNavRouteChildren {
  AuthenticatedNavBuildingsIndexRoute: typeof AuthenticatedNavBuildingsIndexRoute
}

const AuthenticatedNavRouteChildren: AuthenticatedNavRouteChildren = {
  AuthenticatedNavBuildingsIndexRoute: AuthenticatedNavBuildingsIndexRoute,
}

const AuthenticatedNavRouteWithChildren =
  AuthenticatedNavRoute._addFileChildren(AuthenticatedNavRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMapRoute: typeof AuthenticatedMapRouteWithChildren
  AuthenticatedNavRoute: typeof AuthenticatedNavRouteWithChildren
  AuthenticatedAuthAccountRoute: typeof AuthenticatedAuthAccountRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMapRoute: AuthenticatedMapRouteWithChildren,
  AuthenticatedNavRoute: AuthenticatedNavRouteWithChildren,
  AuthenticatedAuthAccountRoute: AuthenticatedAuthAccountRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
