/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssetAttachmentResponse,
  AssetResponse,
  ErrorModel,
  ListAssetsParams,
  UploadAssetParams
} from '../model';


export type HTTPStatusCode1xx = 100 | 101 | 102 | 103;
export type HTTPStatusCode2xx = 200 | 201 | 202 | 203 | 204 | 205 | 206 | 207;
export type HTTPStatusCode3xx = 300 | 301 | 302 | 303 | 304 | 305 | 307 | 308;
export type HTTPStatusCode4xx = 400 | 401 | 402 | 403 | 404 | 405 | 406 | 407 | 408 | 409 | 410 | 411 | 412 | 413 | 414 | 415 | 416 | 417 | 418 | 419 | 420 | 421 | 422 | 423 | 424 | 426 | 428 | 429 | 431 | 451;
export type HTTPStatusCode5xx = 500 | 501 | 502 | 503 | 504 | 505 | 507 | 511;
export type HTTPStatusCodes = HTTPStatusCode1xx | HTTPStatusCode2xx | HTTPStatusCode3xx | HTTPStatusCode4xx | HTTPStatusCode5xx;




const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listAssetsResponse200 = {
  data: AssetAttachmentResponse[]
  status: 200
}

export type listAssetsResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type listAssetsResponseSuccess = (listAssetsResponse200) & {
  headers: Headers;
};
export type listAssetsResponseError = (listAssetsResponseDefault) & {
  headers: Headers;
};

export type listAssetsResponse = (listAssetsResponseSuccess | listAssetsResponseError)

export const getListAssetsUrl = (params: ListAssetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assets?${stringifiedParams}` : `/api/assets`
}

/**
 * @summary Lists the files attached to a location or a building
 */
export const listAssets = async (params: ListAssetsParams, options?: RequestInit): Promise<listAssetsResponse> => {

  const res = await fetch(getListAssetsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listAssetsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listAssetsResponse
}





export const getListAssetsQueryKey = (params?: ListAssetsParams,) => {
    return [
    `/api/assets`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAssetsQueryOptions = <TData = Awaited<ReturnType<typeof listAssets>>, TError = ErrorModel>(params: ListAssetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssetsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssets>>> = ({ signal }) => listAssets(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAssetsQueryResult = NonNullable<Awaited<ReturnType<typeof listAssets>>>
export type ListAssetsQueryError = ErrorModel


export function useListAssets<TData = Awaited<ReturnType<typeof listAssets>>, TError = ErrorModel>(
 params: ListAssetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssets>>,
          TError,
          Awaited<ReturnType<typeof listAssets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssets<TData = Awaited<ReturnType<typeof listAssets>>, TError = ErrorModel>(
 params: ListAssetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssets>>,
          TError,
          Awaited<ReturnType<typeof listAssets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssets<TData = Awaited<ReturnType<typeof listAssets>>, TError = ErrorModel>(
 params: ListAssetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Lists the files attached to a location or a building
 */

export function useListAssets<TData = Awaited<ReturnType<typeof listAssets>>, TError = ErrorModel>(
 params: ListAssetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAssetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type uploadAssetResponse201 = {
  data: AssetResponse
  status: 201
}

export type uploadAssetResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 201>
}

export type uploadAssetResponseSuccess = (uploadAssetResponse201) & {
  headers: Headers;
};
export type uploadAssetResponseError = (uploadAssetResponseDefault) & {
  headers: Headers;
};

export type uploadAssetResponse = (uploadAssetResponseSuccess | uploadAssetResponseError)

export const getUploadAssetUrl = (params?: UploadAssetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assets?${stringifiedParams}` : `/api/assets`
}

/**
 * @summary Uploads a file, optionally attaching it to a location or a building
 */
export const uploadAsset = async (uploadAssetBody: Blob,
    params?: UploadAssetParams, options?: RequestInit): Promise<uploadAssetResponse> => {

  const res = await fetch(getUploadAssetUrl(params),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/octet-stream', ...options?.headers },
    body: uploadAssetBody
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: uploadAssetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as uploadAssetResponse
}





export const getUploadAssetMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAsset>>, TError,{data: Blob;params?: UploadAssetParams}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAsset>>, TError,{data: Blob;params?: UploadAssetParams}, TContext> => {

const mutationKey = ['uploadAsset'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAsset>>, {data: Blob;params?: UploadAssetParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadAsset(data,params,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadAssetMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAsset>>>
    export type UploadAssetMutationBody = Blob
    export type UploadAssetMutationError = ErrorModel

    /**
 * @summary Uploads a file, optionally attaching it to a location or a building
 */
export const useUploadAsset = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAsset>>, TError,{data: Blob;params?: UploadAssetParams}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAsset>>,
        TError,
        {data: Blob;params?: UploadAssetParams},
        TContext
      > => {
      return useMutation(getUploadAssetMutationOptions(options), queryClient);
    }
    export type getAssetContentResponse200 = {
  data: Blob
  status: 200
}

export type getAssetContentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 200>
}

export type getAssetContentResponseSuccess = (getAssetContentResponse200) & {
  headers: Headers;
};
export type getAssetContentResponseError = (getAssetContentResponseDefault) & {
  headers: Headers;
};

export type getAssetContentResponse = (getAssetContentResponseSuccess | getAssetContentResponseError)

export const getGetAssetContentUrl = (id: string,) => {




  return `/api/assets/${id}/content`
}

/**
 * @summary Returns the bytes of the asset with the provided id
 */
export const getAssetContent = async (id: string, options?: RequestInit): Promise<getAssetContentResponse> => {

  const res = await fetch(getGetAssetContentUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: getAssetContentResponse['data'] = body as getAssetContentResponse['data']
  return { data, status: res.status, headers: res.headers } as getAssetContentResponse
}





export const getGetAssetContentQueryKey = (id: string,) => {
    return [
    `/api/assets/${id}/content`
    ] as const;
    }


export const getGetAssetContentQueryOptions = <TData = Awaited<ReturnType<typeof getAssetContent>>, TError = ErrorModel>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssetContentQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssetContent>>> = ({ signal }) => getAssetContent(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssetContentQueryResult = NonNullable<Awaited<ReturnType<typeof getAssetContent>>>
export type GetAssetContentQueryError = ErrorModel


export function useGetAssetContent<TData = Awaited<ReturnType<typeof getAssetContent>>, TError = ErrorModel>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetContent>>,
          TError,
          Awaited<ReturnType<typeof getAssetContent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetContent<TData = Awaited<ReturnType<typeof getAssetContent>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssetContent>>,
          TError,
          Awaited<ReturnType<typeof getAssetContent>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssetContent<TData = Awaited<ReturnType<typeof getAssetContent>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Returns the bytes of the asset with the provided id
 */

export function useGetAssetContent<TData = Awaited<ReturnType<typeof getAssetContent>>, TError = ErrorModel>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssetContent>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssetContentQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteAssetAttachmentResponse204 = {
  data: void
  status: 204
}

export type deleteAssetAttachmentResponseDefault = {
  data: ErrorModel
  status: Exclude<HTTPStatusCodes, 204>
}

export type deleteAssetAttachmentResponseSuccess = (deleteAssetAttachmentResponse204) & {
  headers: Headers;
};
export type deleteAssetAttachmentResponseError = (deleteAssetAttachmentResponseDefault) & {
  headers: Headers;
};

export type deleteAssetAttachmentResponse = (deleteAssetAttachmentResponseSuccess | deleteAssetAttachmentResponseError)

export const getDeleteAssetAttachmentUrl = (id: string,) => {




  return `/api/attachments/${id}`
}

/**
 * The file goes too, unless something else still points at it.
 * @summary Removes a file from the location or building it is attached to
 */
export const deleteAssetAttachment = async (id: string, options?: RequestInit): Promise<deleteAssetAttachmentResponse> => {

  const res = await fetch(getDeleteAssetAttachmentUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteAssetAttachmentResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteAssetAttachmentResponse
}





export const getDeleteAssetAttachmentMutationOptions = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssetAttachment>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssetAttachment>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteAssetAttachment'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssetAttachment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteAssetAttachment(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssetAttachmentMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssetAttachment>>>

    export type DeleteAssetAttachmentMutationError = ErrorModel

    /**
 * @summary Removes a file from the location or building it is attached to
 */
export const useDeleteAssetAttachment = <TError = ErrorModel,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssetAttachment>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssetAttachment>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteAssetAttachmentMutationOptions(options), queryClient);
    }
