/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * nimap API
 * OpenAPI spec version: dev
 */
import * as zod from 'zod';


/**
 * @summary Returns all device models, optionally narrowed to a device type or a manufacturer
 */
export const ListDeviceModelsQueryParams = zod.object({
  "status": zod.array(zod.enum(['planned', 'active', 'decommissioned', 'archived'])).optional().describe('Lifecycle statuses to include. Defaults to planned and active, which keeps models that are no longer available\/used out of the default lists without hiding them from a direct lookup.'),
  "deviceTypeId": zod.string().optional().describe('Only return models of this device type. Omit it to list models of every type.'),
  "manufacturerId": zod.string().optional().describe('Only return models made by this manufacturer. Omit it to list models of every manufacturer.'),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional().describe('Only return models mounted this way. Omit it to list models however they are mounted.')
})

export const ListDeviceModelsResponseItem = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "depthMm": zod.int().optional(),
  "deviceType": zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
}),
  "heightMm": zod.int().optional(),
  "id": zod.string(),
  "manufacturer": zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
}),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().optional()
})
export const ListDeviceModelsResponse = zod.array(ListDeviceModelsResponseItem)

/**
 * @summary Creates a device model
 */









export const CreateDeviceModelBody = zod.object({
  "depthMm": zod.int().min(1).optional(),
  "deviceTypeId": zod.string(),
  "heightMm": zod.int().min(1).optional(),
  "manufacturerId": zod.string(),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().min(1).optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().optional().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().optional().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().min(1).optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().min(1).optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().min(1).optional()
})

export const CreateDeviceModelResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "depthMm": zod.int().optional(),
  "deviceType": zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
}),
  "heightMm": zod.int().optional(),
  "id": zod.string(),
  "manufacturer": zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
}),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().optional()
})

/**
 * @summary Deletes the device model with the provided id
 */
export const DeleteDeviceModelParams = zod.object({
  "id": zod.string()
})

export const DeleteDeviceModelResponse = zod.void()

/**
 * @summary Returns the device model with the provided id
 */
export const GetDeviceModelParams = zod.object({
  "id": zod.string()
})

export const GetDeviceModelResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "depthMm": zod.int().optional(),
  "deviceType": zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
}),
  "heightMm": zod.int().optional(),
  "id": zod.string(),
  "manufacturer": zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
}),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().optional()
})

/**
 * @summary Updates the device model with the provided id
 */
export const UpdateDeviceModelParams = zod.object({
  "id": zod.string()
})










export const UpdateDeviceModelBody = zod.object({
  "depthMm": zod.int().min(1).optional(),
  "deviceTypeId": zod.string(),
  "heightMm": zod.int().min(1).optional(),
  "manufacturerId": zod.string(),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string().min(1),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().min(1).optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().optional().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().optional().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().min(1).optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().min(1).optional(),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().min(1).optional()
})

export const UpdateDeviceModelResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "depthMm": zod.int().optional(),
  "deviceType": zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
}),
  "heightMm": zod.int().optional(),
  "id": zod.string(),
  "manufacturer": zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
}),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().optional()
})

/**
 * @summary Updates the status of the device model with the provided id
 */
export const UpdateDeviceModelStatusParams = zod.object({
  "id": zod.string()
})

export const UpdateDeviceModelStatusBody = zod.object({
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived'])
})

export const UpdateDeviceModelStatusResponse = zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "depthMm": zod.int().optional(),
  "deviceType": zod.object({
  "code": zod.string(),
  "color": zod.string(),
  "icon": zod.string().describe('A lucide icon name'),
  "id": zod.string(),
  "name": zod.string(),
  "sortOrder": zod.int()
}),
  "heightMm": zod.int().optional(),
  "id": zod.string(),
  "manufacturer": zod.object({
  "$schema": zod.url().optional().describe('A URL to the JSON Schema for this object.'),
  "createdAt": zod.iso.datetime({"offset":true}),
  "id": zod.string(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "website": zod.string().optional()
}),
  "mounting": zod.enum(['rack', 'wall', 'desktop', 'din_rail', 'ceiling', 'pole', 'embedded', 'other']).optional(),
  "name": zod.string(),
  "notes": zod.string().optional(),
  "partNumber": zod.string().optional(),
  "poeBudgetWatts": zod.int().optional().describe('Total power the model can supply over PoE, in watts; only with poeOut'),
  "poeIn": zod.boolean().describe('Can be powered over Ethernet'),
  "poeInStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The PoE standard the model needs when powered over Ethernet; only with poeIn'),
  "poeOut": zod.boolean().describe('Can power other devices over Ethernet'),
  "poeOutStandard": zod.enum(['af', 'at', 'bt', 'passive']).optional().describe('The highest PoE standard the model supplies; only with poeOut'),
  "powerWattsMax": zod.int().optional().describe('Maximum power draw in watts'),
  "rackUnits": zod.int().optional(),
  "status": zod.enum(['planned', 'active', 'decommissioned', 'archived']),
  "updatedAt": zod.iso.datetime({"offset":true}),
  "variant": zod.string().optional().describe('A hardware revision or variant sold under the same name, such as rev 2'),
  "website": zod.string().optional().describe('The model\'s page on the manufacturer\'s site'),
  "widthMm": zod.int().optional()
})

